/* ============================================================
   Hanasou! — DỮ LIỆU (data.js)
   - PHRASES: 74 cụm câu du lịch (có "đọc kiểu Việt" + cấp độ)
   - WORDS:   300 từ vựng du lịch, mỗi từ 1 câu ví dụ
   - vn = cách đọc gần đúng kiểu tiếng Việt (xem legend ở Cẩm nang)
   ============================================================ */
"use strict";


/* ---------------- CHỦ ĐỀ CỤM CÂU ---------------- */
/* P(id, cat, level, jp, romaji, đọc-kiểu-Việt, nghĩa VI, EN, tip?) */
const P = (id, cat, _lv, jp, ro, vn, vi, en, tip) => ({ id, cat, kind: "p", jp, ro, vn, vi, en, tip });
const PHRASES = [
  // --- Lời chào (Cấp 1) ---
  P("g1","chao",1,"こんにちは","Konnichiwa","côn-ni-chi-oa","Xin chào (ban ngày)","Hello","Dùng từ trưa đến chiều tối. Câu chào an toàn nhất ở Nhật!"),
  P("g2","chao",1,"おはようございます","Ohayō gozaimasu","ô-ha-yôô gô-za-i-ma-su","Chào buổi sáng","Good morning"),
  P("g3","chao",1,"こんばんは","Konbanwa","côn-ban-oa","Chào buổi tối","Good evening"),
  P("g4","chao",1,"さようなら","Sayōnara","sa-yôô-na-la","Tạm biệt (lịch sự)","Goodbye"),
  P("g5","chao",1,"じゃあね・またね","Jaa ne / Mata ne","gia-a-nê / ma-ta-nê","Hẹn gặp lại (thân mật)","See you!","Với bạn bè, nhân viên thân thiện — tự nhiên hơn Sayōnara."),
  P("g6","chao",1,"ありがとうございます","Arigatō gozaimasu","a-li-ga-tôô gô-za-i-ma-su","Cảm ơn (lịch sự)","Thank you","Nói nhanh cho tự nhiên: 'Arigatôô-gozaimas'."),
  P("g7","chao",1,"すみません","Sumimasen","su-mi-ma-sên","Xin lỗi / Cho tôi hỏi","Excuse me / Sorry","Từ đa dụng nhất: gọi phục vụ, hỏi đường, xin lỗi nhẹ."),
  P("g8","chao",1,"ごめんなさい","Gomen nasai","gô-mên-na-sai","Xin lỗi (thật lòng)","I'm sorry"),
  P("g9","chao",1,"はじめまして","Hajimemashite","ha-gi-mê-ma-xi-tê","Rất vui được gặp lần đầu","Nice to meet you"),
  P("g10","chao",1,"おやすみなさい","Oyasumi nasai","ô-ya-su-mi-na-sai","Chúc ngủ ngon","Good night"),
  // --- Câu cần thiết (Cấp 1) ---
  P("e1","chao",1,"はい","Hai","hai","Vâng / Có","Yes"),
  P("e2","chao",1,"いいえ","Iie","ii-ê","Không (phủ định lịch sự)","No"),
  P("e3","chao",1,"英語が話せますか？","Eigo ga hanasemasu ka?","êi-go ga ha-na-sê-mas ka","Bạn nói được tiếng Anh không?","Do you speak English?"),
  P("e4","chao",1,"わかりません","Wakarimasen","oa-ca-li-ma-sên","Tôi không hiểu","I don't understand"),
  P("e5","chao",1,"ゆっくり話してください","Yukkuri hanashite kudasai","yuc-cu-li ha-na-xi-tê cu-đa-sai","Xin nói chậm lại giúp tôi","Please speak slowly"),
  P("e6","tien",1,"いくらですか？","Ikura desu ka?","i-cu-la des ka","Giá bao nhiêu?","How much?","Chỉ vào món đồ rồi nói 'Ikura desu ka?'"),
  P("e7","chao",1,"トイレはどこですか？","Toire wa doko desu ka?","tôi-lê oa đô-ko des ka","Nhà vệ sinh ở đâu?","Where is the toilet?","Mẫu [nơi] + はどこですか = hỏi đường mọi lúc."),
  P("e8","tien",1,"カードで払えますか？","Kādo de haraemasu ka?","caa-đô đê ha-la-ê-mas ka","Trả bằng thẻ được không?","Can I pay by card?"),
  P("e10","chao",1,"大丈夫です","Daijōbu desu","đai-giôô-bu des","Không sao / Ổn mà","It's okay","Cũng dùng để từ chối lịch sự khi bán hàng mời thêm."),
  // --- Ăn uống ---
  P("r1","anuong",1,"これをください","Kore o kudasai","cô-lê ô cu-đa-sai","Cho tôi cái này","This one, please","Chỉ vào ảnh menu + câu này — ăn được mọi nơi!"),
  P("r2","anuong",1,"メニューをください","Menyū o kudasai","mê-nyuu ô cu-đa-sai","Cho tôi xem thực đơn","Menu, please"),
  P("r3","anuong",1,"お水をください","Omizu o kudasai","ô-mi-zu ô cu-đa-sai","Cho tôi ly nước","Water, please"),
  P("r4","anuong",1,"ビールをください","Bīru o kudasai","bii-lu ô cu-đa-sai","Cho tôi ly bia","Beer, please"),
  P("r5","anuong",1,"ごちそうさまでした","Gochisōsama deshita","gô-chi-sôô-sa-ma đê-xi-ta","Cảm ơn vì bữa ăn","Thanks for the meal","Nói khi ra về — đầu bếp sẽ rất vui!"),
  P("r6","anuong",2,"お会計をお願いします","Okaikei o onegai shimasu","ô-cai-kê ô ô-nê-gai xi-mas","Tính tiền giúp tôi","The check, please"),
  P("r7","anuong",2,"お腹がすきました","Onaka ga sukimashita","ô-na-ca ga su-ki-ma-xi-ta","Tôi đói rồi","I'm hungry"),
  P("r8","anuong",2,"おすすめは何ですか？","Osusume wa nan desu ka?","ô-su-su-mê oa nan des ka","Món nào ngon/tiêu biểu?","What do you recommend?"),
  P("r9","anuong",2,"肉は食べません","Niku wa tabemasen","ni-cu oa ta-bê-ma-sên","Tôi không ăn thịt","I don't eat meat"),
  P("r10","anuong",2,"これは辛いですか？","Kore wa karai desu ka?","cô-lê oa ca-la-i des ka","Món này cay không?","Is this spicy?"),
  // --- Mua sắm ---
  P("s1","muasam",1,"これはいくらですか？","Kore wa ikura desu ka?","cô-lê oa i-cu-la des ka","Cái này bao nhiêu tiền?","How much is this?"),
  P("s2","muasam",2,"試着できますか？","Shichaku dekimasu ka?","xi-chac đê-ki-mas ca","Tôi thử đồ được không?","Can I try it on?"),
  P("s3","muasam",1,"少し高いです","Sukoshi takai desu","su-cô-xi ta-ca-i des","Hơi đắt nhỉ","A bit expensive"),
  P("s4","muasam",3,"もう少し安くなりますか？","Mō sukoshi yasuku narimasu ka?","môô su-cô-xi ya-su-cu na-li-mas ca","Bớt giá được không?","Can you make it cheaper?"),
  P("s5","muasam",1,"これにします","Kore ni shimasu","cô-lê ni xi-mas","Tôi lấy cái này","I'll take this one"),
  P("s6","muasam",2,"見てるだけです","Miteru dake desu","mi-tê-lu đa-kê des","Tôi chỉ xem thôi ạ","Just looking","Nói khi nhân viên mời chào — họ sẽ lịch sự lùi ra."),
  P("s7","muasam",1,"袋をください","Fukuro o kudasai","phu-cu-lô ô cu-đa-sai","Cho tôi túi với","A bag, please"),
  P("s8","muasam",3,"免税できますか？","Menzei dekimasu ka?","mên-zê đê-ki-mas ca","Được miễn thuế không?","Tax-free?"),
  // --- Đường & Xe cộ ---
  P("d1","dulich",1,"駅はどこですか？","Eki wa doko desu ka?","ê-ki oa đô-ko des ca","Ga tàu ở đâu?","Where is the station?"),
  P("d2","dulich",2,"道に迷いました","Michi ni mayoimashita","mi-chi ni ma-yo-i-ma-xi-ta","Tôi bị lạc đường","I'm lost","Nói kèm bản đồ trên điện thoại — người Nhật chỉ đường rất nhiệt tình."),
  P("d3","dulich",1,"左","Hidari","hi-đa-li","Bên trái","Left"),
  P("d4","dulich",1,"右","Migi","mi-gi","Bên phải","Right"),
  P("d5","dulich",1,"まっすぐ","Massugu","ma-s-su-gu","Đi thẳng","Straight"),
  P("d6","dulich",1,"遠いですか？","Tōi desu ka?","tôô-i des ca","Có xa không?","Is it far?"),
  P("d7","dulich",1,"ここはどこですか？","Koko wa doko desu ka?","cô-cô oa đô-ko des ca","Đây là đâu? (chỉ bản đồ)","Where is this?"),
  P("d8","dulich",2,"ここで止めてください","Koko de tomete kudasai","cô-cô đê tô-mê-tê cu-đa-sai","Dừng ở đây giúp tôi","Stop here, please"),
  P("d9","dulich",2,"東京駅行きはどれですか？","Tōkyō-eki-yuki wa dore desu ka?","tôô-kyôô-ê-ki-yu-ki oa đô-lê des ca","Chuyến nào đi ga Tokyo?","Which train goes to Tokyo Station?"),
  P("d10","dulich",2,"大阪まで一枚ください","Ōsaka made ichimai kudasai","ôô-sa-ca ma-đê i-chi-mai cu-đa-sai","Cho tôi 1 vé đến Osaka","One ticket to Osaka, please"),
  // --- Khách sạn & Khẩn cấp ---
  P("h1","khan",2,"予約しています","Yoyaku shite imasu","yo-ya-cu xi-tê i-mas","Tôi có đặt phòng trước","I have a reservation"),
  P("h2","khan",2,"チェックインをお願いします","Chekkuin o onegai shimasu","chêc-cuin ô ô-nê-gai xi-mas","Tôi muốn nhận phòng","Check-in, please"),
  P("h3","khan",3,"チェックアウトは何時ですか？","Chekkuauto wa nanji desu ka?","chêc-cu â-ut oa nan-gi des ca","Trả phòng mấy giờ ạ?","What time is checkout?"),
  P("h4","khan",2,"Wi-Fiのパスワードを教えてください","Wi-Fi no pasuwādo o oshiete kudasai","oai-fai nô pas-uaa-đô ô ô-xiê-tê cu-đa-sai","Cho tôi xin mật khẩu Wi-Fi","Wi-Fi password, please"),
  // --- Số & Tiền ---
  P("n1","tien",1,"いち・に・さん","Ichi, ni, san","i-chi, ni, san","1 · 2 · 3","One, two, three"),
  P("n2","tien",1,"よん・ご・ろく","Yon, go, roku","yôn, gô, lô-cu","4 · 5 · 6","Four, five, six"),
  P("n3","tien",1,"なな・はち・きゅう","Nana, hachi, kyū","na-na, ha-chi, cyuu","7 · 8 · 9","Seven, eight, nine"),
  P("n4","tien",1,"じゅう","Jū","juu","10","Ten"),
  P("n5","tien",1,"ひゃく","Hyaku","hya-cu","100","One hundred"),
  P("n6","tien",1,"せん","Sen","sên","1.000","One thousand"),
  P("n7","tien",2,"まん","Man","man","10.000 (1 man yên)","Ten thousand","Ở Nhật tính bằng 'man': 1 man yên ≈ hơn 1,7 triệu VND."),
  P("n8","tien",2,"きゅうひゃくごじゅうえん","Kyūhyaku gojū en","cyuu-hya-cu gô-juu ên","950 yên","950 yen","Luyện nghe giá tiền: hyaku 100 · sen 1000 · man 10000."),
  // --- Trò chuyện ---
  P("t1","chuyen",1,"わたしの名前は〜です","Watashi no namae wa ~ desu","oa-ta-xi nô na-ma-ê oa ~ des","Tôi tên là ~","My name is ~"),
  P("t2","chuyen",1,"ベトナムから来ました","Betonamu kara kimashita","bê-tô-na-mu ca-la ki-ma-xi-ta","Tôi đến từ Việt Nam","I'm from Vietnam"),
  P("t3","chuyen",2,"〜から来ました","~ kara kimashita","~ ca-la ki-ma-xi-ta","Tôi đến từ ~","I'm from ~"),
  P("t4","chuyen",1,"すしが好きです","Sushi ga suki desu","su-xi ga su-ki des","Tôi thích sushi","I like sushi"),
  P("t5","chuyen",1,"おいしい！","Oishii!","ô-i-xii!","Ngon quá!","Delicious!","Câu khiến đầu bếp mỉm cười nhất."),
  P("t6","chuyen",1,"すごい！","Sugoi!","su-gôi!","Tuyệt quá! (Wow!)","Amazing!"),
  P("t7","chuyen",1,"きれい！","Kirei!","ki-lêi!","Đẹp quá!","Beautiful!"),
  P("t8","chuyen",1,"また明日","Mata ashita","ma-ta a-xi-ta","Hẹn gặp lại ngày mai","See you tomorrow"),
  P("t9","chuyen",2,"いい一日を","Ii ichinichi o","ii i-chi-ni-chi ô","Chúc một ngày tốt lành","Have a good day"),
  P("t10","chuyen",2,"日本語は難しいですね","Nihongo wa muzukashii desu ne","ni-hôn-gô oa mu-zu-ca-xii des nê","Tiếng Nhật khó nhỉ 😅","Japanese is hard, isn't it?","Câu phá băng kinh điển — người Nhật sẽ cười và dạy bạn ngay!"),
  P("r11","anuong",1,"いただきます","Itadakimasu","i-ta-đa-ki-mas","Con xin dùng bữa ạ","Let's eat (thanks for the food)","Nói trước khi ăn — chắp tay, cúi nhẹ đầu. Người Nhật rất quý điều này!"),
  P("r12","anuong",1,"お箸をください","Ohashi o kudasai","ô-ha-xi ô cu-đa-sai","Cho tôi đôi đũa","Chopsticks, please"),
  P("r13","anuong",2,"乾杯！","Kanpai!","can-pai!","Cạn ly!","Cheers!","Nâng ngang tầm ly khi 'can-pai' nhé!"),
  P("r14","anuong",3,"ベジタリアンです","Bejitarian desu","bê-gi-ta-li-an des","Tôi ăn chay","I'm vegetarian","Kết hợp với 肉は食べません để chốt món."),
  P("g11","chao",2,"どういたしまして","Dōitashimashite","đôô-i-ta-xi-ma-xi-tê","Không có gì đâu ạ","You're welcome"),
  P("t11","chuyen",3,"すばらしい！","Subarashii!","su-ba-la-xii!","Tuyệt vời!","Splendid!","Khen cảnh đẹp, món ăn — mạnh hơn Sugoi."),
  P("d11","thamquan",2,"写真を撮ってもいいですか？","Shashin o tottemo ii desu ka?","xa-xin ô tô-t-tê-mô ii des ca","Cho tôi chụp hình được không?","May I take a photo?","Lịch sự khi chụp người khác hoặc trong đền chùa."),
];

/* ---------------- TỪ VỰNG (300) ---------------- */
/* ---------------- DANH MỤC (theo tình huống) ---------------- */
const CATS = [
  { id: "chao",     emoji: "👋", name: "Chào hỏi & Lịch sự",   jp: "あいさつ" },
  { id: "anuong",   emoji: "🍜", name: "Ăn uống",              jp: "食べ物・レストラン" },
  { id: "tien",     emoji: "💴", name: "Số, Giờ & Giá",        jp: "数字・時間・お金" },
  { id: "dulich",   emoji: "🚃", name: "Đi lại & Hỏi đường",   jp: "交通・場所" },
  { id: "muasam",   emoji: "🛍️", name: "Mua sắm & Đồ vật",     jp: "買い物・物" },
  { id: "khan",     emoji: "🏨", name: "Khách sạn",            jp: "ホテル" },
  { id: "thamquan", emoji: "🗾", name: "Tham quan",            jp: "観光" },
  { id: "chuyen",   emoji: "💬", name: "Trò chuyện & Cảm xúc", jp: "雑談・気持ち" },
  { id: "hoi",      emoji: "❓", name: "Hỏi & Động từ",        jp: "疑問詞・動詞" },
];

/* W(id, cat, level, jp, romaji, đọc-kiểu-Việt, nghĩa VI, ví dụJP, ví dụRO, ví dụĐỌC-Việt, ví dụVI) */
const W = (id, cat, _lv, jp, ro, vn, vi, ej, er, ev, evi) =>
  ({ id, cat, kind: "w", jp, ro, vn, vi, ex: { jp: ej, ro: er, vn: ev, vi: evi } });
const WORDS = [
  // ===== 1. ĐỒ ĂN & UỐNG (30) =====
  W("vanuong-1","anuong",1,"水","mizu","mi-zu","nước","お水をください","Omizu o kudasai","ô-mi-zu ô cu-đa-sai","Cho tôi nước với"),
  W("vanuong-2","anuong",1,"お茶","ocha","ô-cha","trà","お茶をください","Ocha o kudasai","ô-cha ô cu-đa-sai","Cho tôi trà với"),
  W("vanuong-3","anuong",1,"コーヒー","kōhī","côô-hii","cà phê","コーヒーが好きです","Kōhī ga suki desu","côô-hii ga su-ki des","Tôi thích cà phê"),
  W("vanuong-4","anuong",1,"ご飯","gohan","gô-han","cơm / bữa ăn","ご飯を食べましょう","Gohan o tabemashō","gô-han ô ta-bê-ma-xôô","Cùng ăn cơm nhé"),
  W("vanuong-5","anuong",1,"パン","pan","pan","bánh mì","このパンはおいしい","Kono pan wa oishii","co-no pan oa ô-i-xii","Bánh mì này ngon"),
  W("vanuong-6","anuong",1,"肉","niku","ni-cu","thịt","肉は食べません","Niku wa tabemasen","ni-cu oa ta-bê-ma-sên","Tôi không ăn thịt"),
  W("vanuong-7","anuong",1,"魚","sakana","sa-ca-na","cá","魚が好きです","Sakana ga suki desu","sa-ca-na ga su-ki des","Tôi thích cá"),
  W("vanuong-8","anuong",1,"野菜","yasai","ya-sai","rau củ","野菜をたくさん食べます","Yasai o takusan tabemasu","ya-sai ô ta-cu-san ta-bê-mas","Tôi ăn nhiều rau"),
  W("vanuong-9","anuong",1,"果物","kudamono","cu-đa-mô-no","trái cây","果物は好きですか","Kudamono wa suki desu ka","cu-đa-mô-no oa su-ki des ca","Bạn có thích trái cây không?"),
  W("vanuong-10","anuong",1,"卵","tamago","ta-ma-gô","trứng","卵をください","Tamago o kudasai","ta-ma-gô ô cu-đa-sai","Cho tôi trứng với"),
  W("vanuong-11","anuong",1,"ビール","bīru","bii-lu","bia","ビールをもう一杯","Bīru o mō ippai","bii-lu ô môô ip-pai","Cho thêm một cốc bia nữa"),
  W("vanuong-12","anuong",2,"お酒","osake","ô-sa-kê","rượu","お酒は飲めますか","Osake wa nomemasu ka","ô-sa-kê oa no-mê-mas ca","Bạn uống được rượu không?"),
  W("vanuong-13","anuong",2,"牛肉","gyūniku","ghiuu-ni-cu","thịt bò","牛肉をください","Gyūniku o kudasai","gyuu-ni-cu ô cu-đa-sai","Cho tôi thịt bò"),
  W("vanuong-14","anuong",2,"豚肉","butaniku","bu-ta-ni-cu","thịt heo","豚肉は大丈夫です","Butaniku wa daijōbu desu","bu-ta-ni-cu oa đai-giôô-bu des","Thịt heo thì tôi ăn được ạ"),
  W("vanuong-15","anuong",2,"鶏肉","toriniku","tô-li-ni-cu","thịt gà","鶏肉がいいです","Toriniku ga ii desu","tô-li-ni-cu ga ii des","Tôi muốn thịt gà"),
  W("vanuong-16","anuong",2,"味噌汁","misoshiru","mi-xô-xi-lu","canh miso","味噌汁が飲みたい","Misoshiru ga nomitai","mi-xô-xi-lu ga no-mi-đai","Tôi muốn uống canh miso"),
  W("vanuong-17","anuong",2,"弁当","bentō","bên-tôô","cơm hộp","弁当を一つください","Bentō o hitotsu kudasai","bên-tôô ô hi-tô-tsu cu-đa-sai","Cho tôi một hộp cơm"),
  W("vanuong-18","anuong",2,"おにぎり","onigiri","ô-ni-ghi-li","cơm nắm","おにぎりを二つ","Onigiri o futatsu","ô-ni-gi-li ô phu-tat-su","Cho hai chiếc cơm nắm"),
  W("vanuong-19","anuong",2,"デザート","dezāto","đê-zaa-tô","món tráng miệng","デザートはありますか","Dezāto wa arimasu ka","đê-zaa-tô oa a-li-mas ca","Có món tráng miệng không?"),
  W("vanuong-20","anuong",2,"アイスクリーム","aisukurīm","ai-su-cu-lii-mu","kem","アイスクリームが食べたい","Aisukurīm ga tabetai","ai-su-cu-lii-mu ga ta-bê-đai","Tôi muốn ăn kem"),
  W("vanuong-21","anuong",3,"スープ","sūpu","suu-pu","súp","このスープは熱いです","Kono sūpu wa atsui desu","co-no suu-pu oa at-sui des","Súp này nóng lắm"),
  W("vanuong-22","anuong",3,"サラダ","sarada","sa-la-đa","salát","サラダをください","Sarada o kudasai","sa-la-đa ô cu-đa-sai","Cho tôi salát"),
  W("vanuong-23","anuong",3,"チーズ","chīzu","chii-zu","phô mai","チーズが入っていますか","Chīzu ga haitte imasu ka","chii-du ga hai-tê i-mas ca","Có phô mai trong này không?"),
  W("vanuong-24","anuong",3,"トマト","tomato","tô-ma-tô","cà chua","トマトは入っていますか","Tomato wa haitte imasu ka","tô-ma-tô oa hai-tê i-mas ca","Có cà chua không ạ?"),
  W("vanuong-25","anuong",3,"みかん","mikan","mi-can","cam","みかんを三つ","Mikan o mittsu","mi-can ô mit-tsu","Cho ba quả cam"),
  W("vanuong-26","anuong",3,"いちご","ichigo","i-chi-gô","dâu tây","いちごが大好き","Ichigo ga daisuki","i-chi-gô ga đai-su-ki","Tôi cực thích dâu tây"),
  W("vanuong-27","anuong",2,"お湯","oyu","ô-yu","nước nóng","お湯をください","Oyu o kudasai","ô-yu ô cu-đa-sai","Cho tôi nước nóng"),
  W("vanuong-28","anuong",3,"氷","kōri","côô-li","đá lạnh","氷は入りません","Kōri wa irimasen","côô-li oa i-li-ma-sên","Cho tôi không bỏ đá"),
  W("vanuong-29","anuong",3,"ストロー","sutorō","su-tô-lôô","ống hút","ストローをください","Sutorō o kudasai","su-tô-lôô ô cu-đa-sai","Cho tôi ống hút"),
  W("vanuong-30","anuong",3,"おかわり","okawari","ô-ca-oa-li","thêm phần nữa","おかわりをください","Okawari o kudasai","ô-ca-oa-li ô cu-đa-sai","Cho tôi thêm phần nữa"),
  // ===== 2. SỐ & TIỀN (30) =====
  W("sotien-1","tien",1,"一","ichi","i-chi","một","一つください","Hitotsu kudasai","hi-tô-tsu cu-đa-sai","Cho tôi một cái"),
  W("sotien-2","tien",1,"二","ni","ni","hai","二人です","Futari desu","phu-ta-li des","Bọn tôi đi hai người"),
  W("sotien-3","tien",1,"三","san","san","ba","三つください","Mittsu kudasai","mit-tsu cu-đa-sai","Cho tôi ba cái"),
  W("sotien-4","tien",1,"四","yôn","yôn","bốn","四時です","Yo-ji desu","yô-ji des","Bốn giờ rồi"),
  W("sotien-5","tien",1,"五","go","gô","năm","五分です","Go-fun desu","gô-phun des","Là 5 phút ạ"),
  W("sotien-6","tien",1,"六","roku","lô-cu","sáu","六時です","Roku-ji desu","lô-cu-ji des","Sáu giờ rồi"),
  W("sotien-7","tien",1,"七","nana","na-na","bảy","七時です","Shichi-ji desu","xi-chi-ji des","Bảy giờ rồi"),
  W("sotien-8","tien",1,"八","hachi","ha-chi","tám","八時です","Hachi-ji desu","ha-chi-ji des","Tám giờ rồi"),
  W("sotien-9","tien",1,"九","kyū","cyuu","chín","九時です","Ku-ji desu","cu-ji des","Chín giờ rồi"),
  W("sotien-10","tien",1,"十","jū","juu","mười","十時です","Jū-ji desu","juu-ji des","Mười giờ rồi"),
  W("sotien-11","tien",1,"百","hyaku","hya-cu","một trăm","百円です","Hyaku-en desu","hya-cu ên des","Một trăm yên"),
  W("sotien-12","tien",1,"千","sen","sên","một nghìn","千円です","Sen-en desu","sên ên des","Một nghìn yên"),
  W("sotien-13","tien",1,"万","man","man","mười nghìn","一万円です","Ichi-man-en desu","i-chi man ên des","Mười nghìn yên"),
  W("sotien-14","tien",1,"円","en","ên","yên (tiền Nhật)","これは五百円です","Kore wa gohyaku-en desu","cô-lê oa gô-hya-cu ên des","Cái này năm trăm yên"),
  W("sotien-15","tien",1,"何時","nanji","nan-gi","mấy giờ","何時ですか","Nanji desu ka","nan-gi des ca","Bây giờ mấy giờ ạ?"),
  W("sotien-16","tien",1,"カード","kādo","caa-đô","thẻ (ngân hàng)","カードで払えます","Kādo de haraemasu","caa-đô đê ha-la-ê-mas","Trả bằng thẻ được"),
  W("sotien-17","tien",2,"お金","okane","ô-ca-nê","tiền","お金が足りません","Okane ga tarimasen","ô-ca-nê ga ta-li-ma-sên","Tôi thiếu tiền"),
  W("sotien-18","tien",2,"値段","nedan","nê-đan","giá cả","値段を見せてください","Nedan o misete kudasai","nê-đan ô mi-sê-tê cu-đa-sai","Cho tôi xem giá với"),
  W("sotien-19","tien",2,"現金","genkin","ghên-kin","tiền mặt","現金で払います","Genkin de haraimasu","ghên-kin đê ha-la-i-mas","Tôi trả bằng tiền mặt"),
  W("sotien-20","tien",2,"お釣り","otsuri","ô-tsu-li","tiền thối","お釣りをもらいました","Otsuri o moraimashita","ô-tsu-li ô mô-la-i-ma-xi-ta","Tôi nhận lại tiền thối"),
  W("sotien-21","tien",2,"半分","hanbun","han-bun","một nửa","半分にしてください","Hanbun ni shite kudasai","han-bun ni xi-tê cu-đa-sai","Giảm còn một nửa giúp tôi"),
  W("sotien-22","tien",2,"全部","zenbu","zên-bu","tất cả","全部でいくらですか","Zenbu de ikura desu ka","zên-bu đê i-cu-la des ca","Tất cả hết bao nhiêu?"),
  W("sotien-23","tien",3,"両替","ryōgae","lyôô-ga-ê","đổi tiền","両替はできますか","Ryōgae wa dekimasu ka","lyôô-ga-ê oa đê-ki-mas ca","Đổi tiền được không?"),
  W("sotien-24","tien",3,"割引","waribiki","oa-li-bi-ki","giảm giá","割引はありますか","Waribiki wa arimasu ka","oa-li-bi-ki oa a-li-mas ca","Có giảm giá không?"),
  W("sotien-25","tien",3,"税込み","zeikomi","zêi-ko-mi","đã gồm thuế","税込みですか","Zeikomi desu ka","zêi-ko-mi des ca","Giá này đã gồm thuế chưa?"),
  W("sotien-26","tien",3,"小銭","kozeni","co-zê-ni","tiền lẻ","小銭がありますか","Kozeni ga arimasu ka","co-zê-ni ga a-li-mas ca","Bạn có tiền lẻ không?"),
  W("sotien-27","tien",3,"もう一度","mō ichido","môô i-chi-đô","một lần nữa","もう一度お願いします","Mō ichido onegai shimasu","môô i-chi-đô ô-nê-gai xi-mas","Làm ơn nói lại một lần"),
  W("sotien-28","tien",3,"ちょうど","chōdo","chôô-đô","vừa đúng","ちょうど千円です","Chōdo sen-en desu","chôô-đô sên ên des","Vừa đúng một nghìn yên"),
  W("sotien-29","tien",3,"約","yaku","ya-cu","khoảng chừng","約一時間かかります","Yaku ichijikan kakarimasu","ya-cu i-chi-gi-can ca-ca-li-mas","Mất khoảng một tiếng"),
  W("sotien-30","tien",3,"領収書","ryōshūsho","lyôô-xuu-xô","hóa đơn","領収書をください","Ryōshūsho o kudasai","lyôô-xuu-xô ô cu-đa-sai","Cho tôi hóa đơn"),
  // ===== 3. THỜI GIAN (30) =====
  W("thoigian-1","tien",1,"今日","kyō","cyôô","hôm nay","今日は晴れです","Kyō wa hare desu","cyôô oa ha-lê des","Hôm nay trời nắng"),
  W("thoigian-2","tien",1,"明日","ashita","a-xi-ta","ngày mai","明日行きます","Ashita ikimasu","a-xi-ta i-ki-mas","Mai tôi sẽ đi"),
  W("thoigian-3","tien",1,"昨日","kinō","ki-nôô","hôm qua","昨日買いました","Kinō kaimashita","ki-nôô ca-i-ma-xi-ta","Hôm qua tôi đã mua"),
  W("thoigian-4","tien",1,"明後日","asatte","a-sat-tê","ngày mốt","明後日帰ります","Asatte kaerimasu","a-sat-tê ca-ê-li-mas","Ngày mốt tôi về"),
  W("thoigian-5","tien",1,"今","ima","i-ma","bây giờ","今何時ですか","Ima nanji desu ka","i-ma nan-gi des ca","Bây giờ mấy giờ?"),
  W("thoigian-6","tien",1,"朝","asa","a-sa","buổi sáng","朝コーヒーを飲みます","Asa kōhī o nomimasu","a-sa côô-hii ô no-mi-mas","Sáng tôi uống cà phê"),
  W("thoigian-7","tien",1,"昼","hiru","hi-lu","buổi trưa","昼ご飯は何ですか","Hiru gohan wa nan desu ka","hi-lu gô-han oa nan des ca","Trưa ăn gì vậy?"),
  W("thoigian-8","tien",1,"夜","yoru","yô-lu","buổi tối","夜は静かです","Yoru wa shizuka desu","yô-lu oa xi-du-ca des","Ban đêm yên tĩnh"),
  W("thoigian-9","tien",1,"時間","jikan","gi-can","thời gian","時間がありません","Jikan ga arimasen","gi-can ga a-li-ma-sên","Không còn thời gian"),
  W("thoigian-10","tien",1,"分","fun","phun","phút","十分待ってください","Juppun matte kudasai","jup-phun mat-tê cu-đa-sai","Chờ mười phút giúp tôi"),
  W("thoigian-11","tien",2,"今週","konshū","con-xuu","tuần này","今週帰ります","Konshū kaerimasu","con-xuu ca-ê-li-mas","Tuần này tôi về"),
  W("thoigian-12","tien",2,"来週","raishū","lai-xuu","tuần sau","来週日本へ行きます","Raishū Nihon e ikimasu","lai-xuu ni-hôn ê i-ki-mas","Tuần sau tôi đi Nhật"),
  W("thoigian-13","tien",2,"週末","shūmatsu","xuu-mat-su","cuối tuần","週末は暇です","Shūmatsu wa hima desu","xuu-mat-su oa hi-ma des","Cuối tuần tôi rảnh"),
  W("thoigian-14","tien",2,"月","tsuki/gatsu","tsu-ki/gat-su","tháng / mặt trăng","三月です","Sangatsu desu","san-gat-su des","Tháng ba rồi"),
  W("thoigian-15","tien",2,"年","toshi/nen","tô-xi/nên","năm","一年に一回","Ichinen ni ikkai","i-chi-nên ni ic-cai","Một năm một lần"),
  W("thoigian-16","tien",2,"午前","gozen","gô-zên","buổi sáng (trước trưa)","午前中に来ます","Gozen chū ni kimasu","gô-zên chuu ni ki-mas","Tôi đến vào buổi sáng"),
  W("thoigian-17","tien",2,"午後","gogo","gô-gô","buổi chiều","午後から出かけます","Gogo kara dekakemasu","gô-gô ca-la đê-ca-kê-mas","Chiều tôi đi ra ngoài"),
  W("thoigian-18","tien",2,"毎日","mainichi","mai-ni-chi","mỗi ngày","毎日勉強します","Mainichi benkyō shimasu","mai-ni-chi bên-cyôô xi-mas","Mỗi ngày tôi học"),
  W("thoigian-19","tien",2,"休み","yasumi","ya-su-mi","ngày nghỉ","明日は休みです","Ashita wa yasumi desu","a-xi-ta oa ya-su-mi des","Ngày mai nghỉ"),
  W("thoigian-20","tien",2,"正午","shōgo","xôô-gô","đúng trưa","正午に出発します","Shōgo ni shuppatsu shimasu","xôô-gô ni xup-pat-su xi-mas","Đúng trưa khởi hành"),
  W("thoigian-21","tien",2,"今晩","konban","con-ban","tối nay","今晩は寒いです","Konban wa samui desu","con-ban oa sa-mui des","Tối nay lạnh"),
  W("thoigian-22","tien",3,"まもなく","mamonaku","ma-mô-na-cu","ngay sau đây","まもなく出発します","Mamonaku shuppatsu shimasu","ma-mô-na-cu xup-pat-su xi-mas","Ngay sau đây sẽ khởi hành"),
  W("thoigian-23","tien",3,"祝日","shukujitsu","xu-cu-gi-tsu","ngày lễ","祝日は休みです","Shukujitsu wa yasumi desu","xu-cu-gi-tsu oa ya-su-mi des","Ngày lễ thì nghỉ"),
  W("thoigian-24","tien",3,"平日","heijitsu","hêi-gi-tsu","ngày thường","平日はすいています","Heijitsu wa suite imasu","hêi-gi-tsu oa sui-tê i-mas","Ngày thường vắng khách"),
  W("thoigian-25","tien",3,"予定","yotei","yô-têi","kế hoạch","予定はありますか","Yotei wa arimasu ka","yô-têi oa a-li-mas ca","Bạn có kế hoạch gì không?"),
  W("thoigian-26","tien",3,"すぐ","sugu","su-gu","ngay lập tức","すぐ行きます","Sugu ikimasu","su-gu i-ki-mas","Tôi đi ngay đây"),
  W("thoigian-27","tien",3,"もうすぐ","mō sugu","môô su-gu","sắp… rồi","もうすぐ着きます","Mō sugu tsukimasu","môô su-gu tsu-ki-mas","Sắp đến rồi"),
  W("thoigian-28","tien",3,"後で","ato de","a-tô đê","sau đó","後で電話します","Ato de denwa shimasu","a-tô đê đên-oa xi-mas","Sau tôi sẽ gọi lại"),
  W("thoigian-29","tien",3,"当日","tōjitsu","tôô-gi-tsu","trong ngày đó","当日に買えます","Tōjitsu ni kaemasu","tôô-gi-tsu ni ca-ê-mas","Mua được ngay trong ngày"),
  W("thoigian-30","tien",3,"前日","zenjitsu","zên-gi-tsu","hôm trước","前日までに予約してください","Zenjitsu made ni yoyaku shite kudasai","zên-gi-tsu ma-đê ni yo-ya-cu xi-tê cu-đa-sai","Đặt trước ngày hôm trước giúp tôi"),
  // ===== 4. ĐỊA ĐIỂM & XE CỘ (30) =====
  W("diadiem-1","dulich",1,"駅","eki","ê-ki","ga tàu","駅はどこですか","Eki wa doko desu ka","ê-ki oa đô-ko des ca","Ga tàu ở đâu?"),
  W("diadiem-2","dulich",1,"空港","kūkō","cuu-côô","sân bay","空港まで行ってください","Kūkō made itte kudasai","cuu-côô ma-đê it-tê cu-đa-sai","Đi đến sân bay giúp tôi"),
  W("diadiem-3","dulich",1,"トイレ","toire","tôi-lê","nhà vệ sinh","トイレはどこですか","Toire wa doko desu ka","tôi-lê oa đô-ko des ca","Nhà vệ sinh ở đâu?"),
  W("diadiem-4","dulich",1,"コンビニ","konbini","con-bi-ni","cửa hàng tiện lợi","近くにコンビニはありますか","Chikaku ni konbini wa arimasu ka","chi-ca-cu ni con-bi-ni oa a-li-mas ca","Gần đây có tiện lợi không?"),
  W("diadiem-5","dulich",1,"ホテル","hoteru","hô-tê-lu","khách sạn","ホテルに戻ります","Hoteru ni modorimasu","hô-tê-lu ni mô-đô-li-mas","Tôi quay lại khách sạn"),
  W("diadiem-6","dulich",1,"銀行","ginkō","ghin-côô","ngân hàng","銀行は何時までですか","Ginkō wa nanji made desu ka","ghin-côô oa nan-gi ma-đê des ca","Ngân hàng mở đến mấy giờ?"),
  W("diadiem-7","dulich",1,"レストラン","resutoran","lê-su-tô-lan","nhà hàng","いいレストランはありますか","Ii resutoran wa arimasu ka","ii lê-su-tô-lan oa a-li-mas ca","Có nhà hàng ngon không?"),
  W("diadiem-8","dulich",1,"バス","basu","ba-su","xe buýt","このバスは駅に行きますか","Kono basu wa eki ni ikimasu ka","co-no ba-su oa ê-ki ni i-ki-mas ca","Xe buýt này đi ga không?"),
  W("diadiem-9","dulich",1,"タクシー","takushī","ta-cu-xii","xe taxi","タクシーを呼んでください","Takushī o yonde kudasai","ta-cu-xii ô yôn-đê cu-đa-sai","Gọi taxi giúp tôi"),
  W("diadiem-10","dulich",1,"電車","densha","đên-xa","tàu điện","電車に乗ります","Densha ni norimasu","đên-xa ni nô-li-mas","Tôi lên tàu điện"),
  W("diadiem-11","dulich",1,"地図","chizu","chi-zu","bản đồ","地図を見せてください","Chizu o misete kudasai","chi-du ô mi-sê-tê cu-đa-sai","Cho tôi xem bản đồ"),
  W("diadiem-12","dulich",2,"新幹線","shinkansen","xin-can-sên","tàu cao tốc","新幹線に乗りたい","Shinkansen ni noritai","xin-can-sên ni nô-li-đai","Tôi muốn đi shinkansen"),
  W("diadiem-13","dulich",2,"切符","kippu","kip-phu","vé","切符を買います","Kippu o kaimasu","kip-phu ô ca-i-mas","Tôi mua vé"),
  W("diadiem-14","dulich",2,"改札","kaisatsu","cai-sat-su","cổng soát vé","改札はどこですか","Kaisatsu wa doko desu ka","cai-sat-su oa đô-ko des ca","Cổng soát vé ở đâu?"),
  W("diadiem-15","dulich",2,"ホーム","hōmu","hôô-mu","sân ga","二番ホームですか","Niban hōmu desu ka","ni-ban hôô-mu des ca","Là sân ga số 2 à?"),
  W("diadiem-19","thamquan",2,"神社","jinja","gin-đa","đền thờ (Shinto)","神社が見たい","Jinja ga mitai","gin-đa ga mi-đai","Tôi muốn xem đền Shinto"),
  W("diadiem-20","thamquan",2,"お寺","otera","ô-tê-la","chùa","お寺へ行きましょう","Otera e ikimashō","ô-tê-la ê i-ki-ma-xôô","Đi chùa thôi!"),
  W("diadiem-21","thamquan",2,"博物館","hakubutsukan","ha-cu-but-su-can","bảo tàng","博物館は面白い","Hakubutsukan wa omoshiroi","ha-cu-but-su-can oa ô-mô-xi-lôi","Bảo tàng rất thú vị"),
  W("diadiem-22","dulich",3,"出口","deguchi","đê-gu-chi","lối ra","出口はどこですか","Deguchi wa doko desu ka","đê-gu-chi oa đô-ko des ca","Lối ra ở đâu?"),
  W("diadiem-23","dulich",3,"入口","iriguchi","i-li-gu-chi","lối vào","入口はあちらです","Iriguchi wa achira desu","i-li-gu-chi oa a-chi-la des","Lối vào ở phía kia"),
  W("diadiem-24","dulich",3,"乗り場","noriba","nô-li-ba","nơi đón / lên xe","タクシーの乗り場はどこですか","Takushī no noriba wa doko desu ka","ta-cu-xii no nô-li-ba oa đô-ko des ca","Điểm đón taxi ở đâu?"),
  W("diadiem-25","dulich",3,"階段","kaidan","cai-đan","cầu thang","階段で行きましょう","Kaidan de ikimashō","cai-đan đê i-ki-ma-xôô","Đi bằng cầu thang nhé"),
  W("diadiem-26","dulich",3,"エレベーター","erebētā","ê-lê-bêê-taa","thang máy","エレベーターはありますか","Erebētā wa arimasu ka","ê-lê-bêê-taa oa a-li-mas ca","Có thang máy không?"),
  W("diadiem-27","dulich",3,"荷物","nimotsu","ni-mô-tsu","hành lý","荷物を見てください","Nimotsu o mite kudasai","ni-mô-tsu ô mi-tê cu-đa-sai","Nhìn giúp tôi hành lý"),
  W("diadiem-28","dulich",3,"近く","chikaku","chi-ca-cu","gần đó","駅の近くです","Eki no chikaku desu","ê-ki no chi-ca-cu des","Gần ga tàu"),
  W("diadiem-29","dulich",3,"向こう","mukō","mu-côô","phía kia","向こうに見えます","Mukō ni miemasu","mu-côô ni mi-ê-mas","Nhìn thấy ở phía kia"),
  W("diadiem-30","dulich",3,"角","kado","ca-đô","ngã rẽ / góc","角を右へ曲がって","Kado o migi e magatte","ca-đô ô mi-gi ê ma-gat-tê","Quẹt phải ở ngã rẽ"),
  // ===== 5. ĐỒ VẬT & MUA SẮM (30) =====
  W("dogvat-1","muasam",1,"これ","kore","cô-lê","cái này","これをください","Kore o kudasai","cô-lê ô cu-đa-sai","Cho tôi cái này"),
  W("dogvat-2","muasam",1,"それ","sore","sô-lê","cái đó","それを見せてください","Sore o misete kudasai","sô-lê ô mi-sê-tê cu-đa-sai","Cho tôi xem cái đó"),
  W("dogvat-3","muasam",1,"あれ","are","a-lê","cái kia","あれは何ですか","Are wa nan desu ka","a-lê oa nan des ca","Cái kia là gì vậy?"),
  W("dogvat-4","muasam",1,"財布","saifu","sai-phu","ví tiền","財布をなくしました","Saifu o nakushimashita","sai-phu ô na-cu-xi-ma-xi-ta","Tôi bị mất ví"),
  W("dogvat-5","muasam",1,"カバン","kaban","ca-ban","cặp / túi","カバンを忘れました","Kaban o wasuremashita","ca-ban ô oa-su-lê-ma-xi-ta","Tôi quên túi xách"),
  W("dogvat-6","muasam",1,"電話","denwa","đên-oa","điện thoại","電話してください","Denwa shite kudasai","đên-oa xi-tê cu-đa-sai","Gọi điện giúp tôi"),
  W("dogvat-7","muasam",1,"カメラ","kamera","ca-mê-la","máy ảnh","写真を撮ってもいいですか","Shashin o tottemo ii desu ka","xa-xin ô tot-tê-mô ii des ca","Chụp hình được không?"),
  W("dogvat-8","muasam",1,"本","hon","hôn","sách","この本はいくらですか","Kono hon wa ikura desu ka","co-no hôn oa i-cu-la des ca","Cuốn sách này bao nhiêu?"),
  W("dogvat-9","muasam",1,"傘","kasa","ca-sa","ô / dù","傘を忘れました","Kasa o wasuremashita","ca-sa ô oa-su-lê-ma-xi-ta","Tôi quên ô"),
  W("dogvat-10","muasam",1,"靴","kutsu","cu-tsu","giày","この靴は高い","Kono kutsu wa takai","co-no cu-tsu oa ta-cai","Đôi giày này đắt"),
  W("dogvat-11","muasam",2,"服","fuku","phu-cu","quần áo","服を買いたい","Fuku o kaitai","phu-cu ô cai-đai","Tôi muốn mua quần áo"),
  W("dogvat-12","muasam",2,"Tシャツ","T-shatsu","tii-xa-tsu","áo thun","白いTシャツをください","Shiroi T-shatsu o kudasai","xi-lôi tii-xa-tsu ô cu-đa-sai","Cho tôi áo thun màu trắng"),
  W("dogvat-13","muasam",2,"サイズ","saizu","sai-zu","cỡ / kích cỡ","大きいサイズはありますか","Ōkii saizu wa arimasu ka","ôô-kii sai-du oa a-li-mas ca","Có cỡ to hơn không?"),
  W("dogvat-14","muasam",2,"色","iro","i-lô","màu sắc","違う色はありますか","Chigau iro wa arimasu ka","chi-gau i-lô oa a-li-mas ca","Có màu khác không?"),
  W("dogvat-15","muasam",2,"店","mise","mi-sê","cửa hàng","この店は何時までですか","Kono mise wa nanji made desu ka","co-no mi-sê oa nan-gi ma-đê des ca","Cửa hàng đóng cửa mấy giờ?"),
  W("dogvat-16","muasam",2,"デパート","depāto","đê-paa-tô","trung tâm thương mại","デパートへ行きましょう","Depāto e ikimashō","đê-paa-tô ê i-ki-ma-xôô","Đi trung tâm thương mại thôi"),
  W("dogvat-18","muasam",2,"お土産","omiyage","ô-mi-ya-gê","quà lưu niệm","お土産を買います","Omiyage o kaimasu","ô-mi-ya-gê ô ca-i-mas","Tôi mua quà lưu niệm"),
  W("dogvat-19","muasam",2,"袋","fukuro","phu-cu-lô","túi (ni lông)","袋はいりません","Fukuro wa irimasen","phu-cu-lô oa i-li-ma-sên","Không cần túi"),
  W("dogvat-20","muasam",2,"レジ","reji","lê-gi","quầy thu ngân","レジはどこですか","Reji wa doko desu ka","lê-gi oa đô-ko des ca","Quầy tính tiền ở đâu?"),
  W("dogvat-21","muasam",3,"値札","nefuda","nê-phu-đa","mác giá","値札を見てください","Nefuda o mite kudasai","nê-phu-đa ô mi-tê cu-đa-sai","Xem giúp tôi mác giá"),
  W("dogvat-22","muasam",3,"在庫","zaiko","zai-cô","hàng tồn / còn hàng","在庫はありますか","Zaiko wa arimasu ka","zai-cô oa a-li-mas ca","Còn hàng không?"),
  W("dogvat-23","muasam",3,"売り場","uriba","u-li-ba","quầy bán","靴の売り場はどこですか","Kutsu no uriba wa doko desu ka","cu-tsu no u-li-ba oa đô-ko des ca","Quầy giày ở đâu?"),
  W("dogvat-24","muasam",3,"半額","hangaku","han-ga-cu","giảm nửa giá","これは半額です","Kore wa hangaku desu","cô-lê oa han-ga-cu des","Cái này giảm nửa giá"),
  W("dogvat-25","muasam",3,"おすすめ","osusume","ô-su-su-mê","điều được đề xuất","おすすめは何ですか","Osusume wa nan desu ka","ô-su-su-mê oa nan des ca","Có gì hay đề xuất không?"),
  W("dogvat-26","muasam",3,"箱","hako","ha-cô","hộp","箱に入れてください","Hako ni irete kudasai","ha-cô ni i-lê-tê cu-đa-sai","Đóng hộp giúp tôi"),
  W("dogvat-27","muasam",3,"ラッピング","rappingu","lap-pin-gu","gói quà","ラッピングをお願いします","Rappingu o onegai shimasu","lap-pin-gu ô ô-nê-gai xi-mas","Làm ơn gói quà giúp tôi"),
  W("dogvat-28","muasam",3,"交換","kōkan","côô-can","đổi hàng","交換できますか","Kōkan dekimasu ka","côô-can đê-ki-mas ca","Đổi hàng được không?"),
  W("dogvat-29","muasam",3,"返品","henpin","hên-pin","trả hàng","返品したいです","Henpin shitai desu","hên-pin xi-đai des","Tôi muốn trả hàng"),
  W("dogvat-30","muasam",3,"名物","meibutsu","mêi-phu-tsu","đặc sản địa phương","ここの名物は何ですか","Koko no meibutsu wa nan desu ka","cô-cô no mêi-phu-tsu oa nan des ca","Nơi này đặc sản gì?"),
  // ===== 6. ĐỘNG TỪ THIẾT YẾU (30) =====
  W("dongtu-1","hoi",1,"食べる","taberu","ta-bê-lu","ăn","何を食べたいですか","Nani o tabetai desu ka","na-ni ô ta-bê-đai des ca","Bạn muốn ăn gì?"),
  W("dongtu-2","hoi",1,"飲む","nomu","nô-mu","uống","何か飲みますか","Nanika nomimasu ka","na-ni-ca nô-mi-mas ca","Bạn uống gì không?"),
  W("dongtu-3","hoi",1,"行く","iku","i-cu","đi","一緒に行きましょう","Issho ni ikimashō","it-xô ni i-ki-ma-xôô","Đi cùng nhau nhé"),
  W("dongtu-4","hoi",1,"来る","kuru","cu-lu","đến","また来ます","Mata kimasu","ma-ta ki-mas","Tôi sẽ lại đến"),
  W("dongtu-5","hoi",1,"買う","kau","ca-u","mua","お土産を買います","Omiyage o kaimasu","ô-mi-ya-gê ô ca-i-mas","Tôi mua quà"),
  W("dongtu-6","hoi",1,"見る","miru","mi-lu","xem / nhìn","見てください","Mite kudasai","mi-tê cu-đa-sai","Nhìn giúp tôi với"),
  W("dongtu-7","hoi",1,"聞く","kiku","ki-cu","nghe / hỏi","人に聞きます","Hito ni kikimasu","hi-tô ni ki-ki-mas","Tôi hỏi người khác"),
  W("dongtu-8","hoi",1,"話す","hanasu","ha-na-su","nói","ゆっくり話してください","Yukkuri hanashite kudasai","yuc-cu-li ha-na-xi-tê cu-đa-sai","Nói chậm giúp tôi"),
  W("dongtu-9","hoi",1,"読む","yomu","yô-mu","đọc","この本を読みます","Kono hon o yomimasu","co-no hôn ô yô-mi-mas","Tôi đọc cuốn sách này"),
  W("dongtu-10","hoi",1,"書く","kaku","ca-cu","viết","名前を書いてください","Namae o kaite kudasai","na-ma-ê ô cai-tê cu-đa-sai","Viết tên giúp tôi"),
  W("dongtu-11","hoi",1,"する","suru","su-lu","làm","何をしますか","Nani o shimasu ka","na-ni ô xi-mas ca","Làm gì nhỉ?"),
  W("dongtu-12","hoi",1,"わかる","wakaru","oa-ca-lu","hiểu","日本語が少しわかります","Nihongo ga sukoshi wakarimasu","ni-hôn-gô ga su-co-xi oa-ca-li-mas","Tôi hiểu chút ít tiếng Nhật"),
  W("dongtu-13","hoi",2,"乗る","noru","nô-lu","lên (xe/tàu)","電車に乗ります","Densha ni norimasu","đên-xa ni nô-li-mas","Tôi lên tàu"),
  W("dongtu-14","hoi",2,"降りる","oriru","ô-li-lu","xuống (xe)","次の駅で降ります","Tsugi no eki de orimasu","tsu-gi no ê-ki đê ô-li-mas","Ga sau tôi xuống"),
  W("dongtu-15","hoi",2,"待つ","matsu","mat-su","chờ","ここで待ってください","Koko de matte kudasai","cô-cô đê mat-tê cu-đa-sai","Chờ ở đây giúp tôi"),
  W("dongtu-16","hoi",2,"休む","yasumu","ya-su-mu","nghỉ","少し休みます","Sukoshi yasumimasu","su-co-xi ya-su-mi-mas","Tôi nghỉ một chút"),
  W("dongtu-17","hoi",2,"使う","tsukau","tsu-cau","dùng","これを使います","Kore o tsukaimasu","cô-lê ô tsu-cai-mas","Tôi dùng cái này"),
  W("dongtu-18","hoi",2,"持つ","motsu","môt-su","cầm / giữ","私が持ちます","Watashi ga mochimasu","oa-ta-xi ga mô-chi-mas","Để tôi cầm"),
  W("dongtu-19","hoi",2,"呼ぶ","yobu","yô-bu","gọi","タクシーを呼びます","Takushī o yobimasu","ta-cu-xii ô yô-bi-mas","Tôi gọi taxi"),
  W("dongtu-20","hoi",2,"手伝う","tetsudau","tê-tsu-đau","giúp đỡ","手伝ってください","Tetsudatte kudasai","tê-tsu-dat-tê cu-đa-sai","Giúp tôi với"),
  W("dongtu-21","hoi",2,"探す","sagasu","sa-ga-su","tìm kiếm","財布を探しています","Saifu o sagashite imasu","sai-phu ô sa-ga-xi-tê i-mas","Tôi đang tìm ví"),
  W("dongtu-22","hoi",2,"撮る","toru","tô-lu","chụp (ảnh)","写真を撮ります","Shashin o torimasu","xa-xin ô tô-li-mas","Tôi chụp hình"),
  W("dongtu-23","hoi",3,"開ける","akeru","a-kê-lu","mở","窓を開けてください","Mado o akete kudasai","ma-đô ô a-kê-tê cu-đa-sai","Mở cửa sổ giúp tôi"),
  W("dongtu-24","hoi",3,"閉める","shimeru","xi-mê-lu","đóng","ドアを閉めてください","Doa o shimete kudasai","đô-a ô xi-mê-tê cu-đa-sai","Đóng cửa giúp tôi"),
  W("dongtu-25","hoi",3,"決める","kimeru","ki-mê-lu","quyết định","これに決めました","Kore ni kimemashita","cô-lê ni ki-mê-ma-xi-ta","Tôi chốt lấy cái này"),
  W("dongtu-26","hoi",3,"集まる","atsumaru","at-su-ma-lu","tập hợp","朝集まりましょう","Asa atsumarimashō","a-sa at-su-ma-li-ma-xôô","Sáng tập hợp nhé"),
  W("dongtu-27","hoi",3,"忘れる","wasureru","oa-su-lê-lu","quên","忘れました","Wasuremashita","oa-su-lê-ma-xi-ta","Tôi quên mất rồi"),
  W("dongtu-28","hoi",3,"取り替える","torikaeru","tô-li-ca-ê-lu","thay / đổi","サイズを取り替えたい","Saizu o torikaetai","sai-du ô tô-li-ca-ê-đai","Tôi muốn đổi cỡ"),
  W("dongtu-29","hoi",3,"予約する","yoyaku suru","yo-ya-cu su-lu","đặt trước","レストランを予約します","Resutoran o yoyaku shimasu","lê-su-tô-lan ô yo-ya-cu xi-mas","Tôi đặt bàn nhà hàng"),
  W("dongtu-30","hoi",3,"遠慮する","enryo suru","ên-lyô su-lu","từ chối lịch sự","遠慮します","Enryo shimasu","ên-lyô xi-mas","Tôi xin phép từ chối ạ"),
  // ===== 7. TÍNH TỪ HỮU ÍCH (30) =====
  W("tinhtu-1","chuyen",1,"おいしい","oishii","ô-i-xii","ngon","これはおいしい","Kore wa oishii","cô-lê oa ô-i-xii","Cái này ngon"),
  W("tinhtu-2","chuyen",1,"高い","takai","ta-cai","đắt / cao","これは高いです","Kore wa takai desu","cô-lê oa ta-cai des","Cái này đắt"),
  W("tinhtu-3","chuyen",1,"安い","yasui","ya-sui","rẻ","この店は安いです","Kono mise wa yasui desu","co-no mi-sê oa ya-sui des","Cửa hàng này rẻ"),
  W("tinhtu-4","chuyen",1,"大きい","ōkii","ôô-kii","to lớn","大きいサイズください","Ōkii saizu kudasai","ôô-kii sai-du cu-đa-sai","Cho cỡ to"),
  W("tinhtu-5","chuyen",1,"小さい","chiisai","chii-sai","nhỏ bé","小さいのはありますか","Chiisai no wa arimasu ka","chii-sai no oa a-li-mas ca","Có cỡ nhỏ không?"),
  W("tinhtu-6","chuyen",1,"新しい","atarashii","a-ta-la-xii","mới","新しい靴を買いました","Atarashii kutsu o kaimashita","a-ta-la-xii cu-tsu ô ca-i-ma-xi-ta","Tôi đã mua giày mới"),
  W("tinhtu-7","chuyen",1,"古い","furui","phu-lui","cũ","古いお寺です","Furui otera desu","phu-lui ô-tê-la des","Là ngôi chùa cũ"),
  W("tinhtu-8","chuyen",1,"いい","ii","ii","tốt / được","いいですね","Ii desu ne","ii des nê","Hay đấy!"),
  W("tinhtu-9","chuyen",1,"かわいい","kawaii","ca-oai-i","dễ thương","とてもかわいい","Totemo kawaii","tô-tê-mô ca-oai-i","Dễ thương quá!"),
  W("tinhtu-10","chuyen",1,"楽しい","tanoshii","ta-nô-xii","vui vẻ","旅行は楽しい","Ryokō wa tanoshii","lyô-côô oa ta-nô-xii","Đi du lịch vui"),
  W("tinhtu-11","chuyen",2,"暑い","atsui","at-sui","nóng","今日は暑いです","Kyō wa atsui desu","cyôô oa at-sui des","Hôm nay nóng"),
  W("tinhtu-12","chuyen",2,"寒い","samui","sa-mui","lạnh","寒いですね","Samui desu ne","sa-mui des nê","Lạnh nhỉ"),
  W("tinhtu-13","chuyen",2,"辛い","karai","ca-lai","cay","これは辛いですか","Kore wa karai desu ka","cô-lê oa ca-lai des ca","Cái này cay không?"),
  W("tinhtu-14","chuyen",2,"甘い","amai","a-mai","ngọt","甘いのが好きです","Amai no ga suki desu","a-mai no ga su-ki des","Tôi thích đồ ngọt"),
  W("tinhtu-15","chuyen",2,"近い","chikai","chi-cai","gần","駅は近いです","Eki wa chikai desu","ê-ki oa chi-cai des","Ga gần lắm"),
  W("tinhtu-16","chuyen",2,"遠い","tōi","tôô-i","xa","遠いですか","Tōi desu ka","tôô-i des ca","Có xa không?"),
  W("tinhtu-17","chuyen",2,"難しい","muzukashii","mu-zu-ca-xii","khó","日本語は難しい","Nihongo wa muzukashii","ni-hôn-gô oa mu-zu-ca-xii","Tiếng Nhật khó"),
  W("tinhtu-18","chuyen",2,"やさしい","yasashii","ya-sa-xii","dễ / tử tế","やさしい人です","Yasashii hito desu","ya-sa-xii hi-tô des","Là người tử tế"),
  W("tinhtu-19","chuyen",2,"赤い","akai","a-cai","màu đỏ","赤いのをください","Akai no o kudasai","a-cai no ô cu-đa-sai","Cho tôi cái màu đỏ"),
  W("tinhtu-20","chuyen",2,"青い","aoi","a-ôi","màu xanh (dương)","青い空がきれい","Aoi sora ga kirei","a-ôi sô-la ga ki-lêi","Bầu trời xanh thật đẹp"),
  W("tinhtu-21","chuyen",3,"静か","shizuka","xi-zu-ca","yên tĩnh","静かなホテルです","Shizuka na hoteru desu","xi-du-ca na hô-tê-lu des","Là khách sạn yên tĩnh"),
  W("tinhtu-22","chuyen",3,"便利","benri","bên-li","tiện lợi","とても便利です","Totemo benri desu","tô-tê-mô bên-li des","Rất tiện lợi"),
  W("tinhtu-23","chuyen",3,"有名","yūmei","yuu-mêi","nổi tiếng","有名なお寺です","Yūmei na otera desu","yuu-mêi na ô-tê-la des","Là ngôi chùa nổi tiếng"),
  W("tinhtu-24","chuyen",3,"軽い","karui","ca-lu-i","nhẹ","これは軽いです","Kore wa karui desu","cô-lê oa ca-lu-i des","Cái này nhẹ"),
  W("tinhtu-25","chuyen",3,"重い","omoi","ô-môi","nặng","荷物が重いです","Nimotsu ga omoi desu","ni-mô-tsu ga ô-môi des","Hành lý nặng"),
  W("tinhtu-26","chuyen",3,"広い","hiroi","hi-lôi","rộng","広い部屋です","Hiroi heya desu","hi-lôi hê-ya des","Căn phòng rộng"),
  W("tinhtu-27","chuyen",3,"狭い","semai","sê-mai","chật hẹp","部屋が狭いです","Heya ga semai desu","hê-ya ga sê-mai des","Căn phòng chật"),
  W("tinhtu-28","chuyen",3,"きれい","kirei","ki-lêi","sạch / đẹp","きれいな街です","Kirei na machi desu","ki-lêi na ma-chi des","Thành phố sạch đẹp"),
  W("tinhtu-29","chuyen",3,"危ない","abunai","a-bu-nai","nguy hiểm","危ないですよ","Abunai desu yo","a-bu-nai des yô","Nguy hiểm đấy!"),
  W("tinhtu-30","chuyen",3,"涼しい","suzushii","su-zu-xii","mát mẻ","秋は涼しい","Aki wa suzushii","a-ki oa su-zu-xii","Mùa thu mát mẻ"),
  // ===== 8. CÂU HỎI & TỪ NỐI (30) =====
  W("cauhoi-1","hoi",1,"何","nani","na-ni","cái gì","これは何ですか","Kore wa nan desu ka","cô-lê oa nan des ca","Đây là cái gì?"),
  W("cauhoi-2","dulich",1,"どこ","doko","đô-cô","ở đâu","トイレはどこですか","Toire wa doko desu ka","tôi-lê oa đô-ko des ca","Nhà vệ sinh ở đâu?"),
  W("cauhoi-3","hoi",1,"だれ","dare","đa-lê","ai","あの人はだれですか","Ano hito wa dare desu ka","a-no hi-tô oa đa-lê des ca","Người kia là ai?"),
  W("cauhoi-4","tien",1,"いくら","ikura","i-cu-la","bao nhiêu (tiền)","これはいくらですか","Kore wa ikura desu ka","cô-lê oa i-cu-la des ca","Cái này bao nhiêu tiền?"),
  W("cauhoi-5","hoi",1,"どう","dō","đôô","thế nào","日本はどうですか","Nihon wa dō desu ka","ni-hôn oa đôô des ca","Nhật Bản thế nào?"),
  W("cauhoi-6","tien",1,"いつ","itsu","i-tsu","khi nào","いつ行きますか","Itsu ikimasu ka","i-tsu i-ki-mas ca","Khi nào đi?"),
  W("cauhoi-7","hoi",1,"どうして","dōshite","đôô-xi-tê","tại sao","どうしてですか","Dōshite desu ka","đôô-xi-tê des ca","Tại sao vậy?"),
  W("cauhoi-8","hoi",1,"どうぞ","dōzo","đôô-zô","mời / xin mời","どうぞ、こちらへ","Dōzo, kochira e","đôô-zô, cô-chi-la ê","Mời bạn bên này"),
  W("cauhoi-9","hoi",1,"ちょっと","chotto","chôt-tô","một chút / khoan","ちょっと待ってください","Chotto matte kudasai","chôt-tô mat-tê cu-đa-sai","Chờ một chút giúp tôi"),
  W("cauhoi-10","hoi",1,"とても","totemo","tô-tê-mô","rất","とてもおいしい","Totemo oishii","tô-tê-mô ô-i-xii","Ngon lắm!"),
  W("cauhoi-11","hoi",2,"いくつ","ikutsu","i-cu-tsu","mấy (cái)","いくつありますか","Ikutsu arimasu ka","i-cu-tsu a-li-mas ca","Có mấy cái?"),
  W("cauhoi-12","hoi",2,"どちら","dochira","đô-chi-la","phía nào / cái nào","どちらへ行きますか","Dochira e ikimasu ka","đô-chi-la ê i-ki-mas ca","Bạn đi phía nào?"),
  W("cauhoi-13","hoi",2,"どれ","dore","đô-lê","cái nào","どれがいいですか","Dore ga ii desu ka","đô-lê ga ii des ca","Cái nào tốt ạ?"),
  W("cauhoi-14","hoi",2,"なぜ","naze","na-zê","tại sao (trang trọng)","なぜ閉まっていますか","Naze shimatte imasu ka","na-zê xi-mat-tê i-mas ca","Sao lại đóng rồi?"),
  W("cauhoi-15","hoi",2,"たぶん","tabun","ta-bun","có lẽ","たぶん大丈夫","Tabun daijōbu","ta-bun đai-giôô-bu","Có lẽ là ổn"),
  W("cauhoi-16","hoi",2,"きっと","kitto","kit-tô","chắc chắn","きっと楽しい","Kitto tanoshii","kit-tô ta-nô-xii","Chắc chắn vui"),
  W("cauhoi-17","hoi",2,"そして","soshite","sô-xi-tê","và rồi","そして行きました","Soshite ikimashita","sô-xi-tê i-ki-ma-xi-ta","Và rồi tôi đã đi"),
  W("cauhoi-18","hoi",2,"でも","demo","đê-mô","nhưng","でも高いです","Demo takai desu","đê-mô ta-cai des","Nhưng mà đắt"),
  W("cauhoi-19","hoi",2,"または","matawa","ma-ta-oa","hoặc","コーヒーまたはお茶","Kōhī matawa ocha","côô-hii ma-ta-oa ô-cha","Cà phê hoặc trà"),
  W("cauhoi-20","hoi",2,"それから","sorekara","sô-lê-ca-la","sau đó","それから駅へ行きます","Sorekara eki e ikimasu","sô-lê-ca-la ê-ki ê i-ki-mas","Sau đó tôi đi ga"),
  W("cauhoi-21","hoi",3,"たとえば","tatoeba","ta-tô-ê-ba","ví dụ","たとえば、すしです","Tatoeba, sushi desu","ta-tô-ê-ba su-xi des","Ví dụ như sushi"),
  W("cauhoi-22","hoi",3,"やっぱり","yappari","yap-pa-li","ra là / rồi ra","やっぱり高いです","Yappari takai desu","yap-pa-li ta-cai des","Ra là đắt nhỉ"),
  W("cauhoi-23","hoi",3,"少し","sukoshi","su-cô-xi","một ít","少し高いです","Sukoshi takai desu","su-cô-xi ta-cai des","Hơi đắt"),
  W("cauhoi-24","hoi",3,"全然","zenzen","zên-zên","hoàn toàn (không)","全然大丈夫","Zenzen daijōbu","zên-zên đai-giôô-bu","Hoàn toàn không sao"),
  W("cauhoi-25","hoi",3,"もう","mō","môô","đã / nữa","もう食べました","Mō tabemashita","môô ta-bê-ma-xi-ta","Tôi đã ăn rồi"),
  W("cauhoi-26","hoi",3,"まだ","mada","ma-đa","vẫn / chưa","まだです","Mada desu","ma-đa des","Vẫn chưa ạ"),
  W("cauhoi-27","hoi",3,"一緒に","issho ni","it-xô ni","cùng nhau","一緒に行きませんか","Issho ni ikimasen ka","it-xô ni i-ki-ma-sên ca","Đi cùng tôi không?"),
  W("cauhoi-28","hoi",3,"ずっと","zutto","zut-tô","mãi / suốt","ずっと日本にいたい","Zutto Nihon ni itai","dut-tô ni-hôn ni i-đai","Tôi muốn ở Nhật mãi"),
  W("cauhoi-29","hoi",3,"もし","moshi","mô-xi","nếu như","もし時間があれば","Moshi jikan ga areba","mô-xi gi-can ga a-lê-ba","Nếu còn thời gian thì…"),
  W("cauhoi-30","hoi",3,"もちろん","mochiron","mô-chi-lôn","đương nhiên","もちろんいいですよ","Mochiron ii desu yo","mô-chi-lôn ii des yô","Đương nhiên là được!"),
  // ===== 9. CẢM XÚC & GIAO TIẾP (30) =====
  W("camxuc-1","chuyen",1,"元気","genki","ghên-ki","khỏe mạnh / vui","元気ですか","Genki desu ka","ghên-ki des ca","Bạn khỏe không?"),
  W("camxuc-2","chuyen",1,"疲れた","tsukareta","tsu-ca-lê-ta","mệt rồi","疲れました","Tsukaremashita","tsu-ca-lê-ma-xi-ta","Tôi mệt rồi"),
  W("camxuc-3","chuyen",1,"嬉しい","ureshii","u-lê-xii","vui mừng","嬉しいです","Ureshii desu","u-lê-xii des","Tôi vui quá"),
  W("camxuc-4","chuyen",1,"悲しい","kanashii","ca-na-xii","buồn","悲しいです","Kanashii desu","ca-na-xii des","Tôi buồn"),
  W("camxuc-5","chuyen",1,"面白い","omoshiroi","ô-mô-xi-lôi","thú vị","この本は面白い","Kono hon wa omoshiroi","co-no hôn oa ô-mô-xi-lôi","Cuốn sách này thú vị"),
  W("camxuc-6","chuyen",1,"つまらない","tsumaranai","tsu-ma-la-nai","nhàm chán","映画はつまらない","Eiga wa tsumaranai","êi-ga oa tsu-ma-la-nai","Phim chán quá"),
  W("camxuc-7","chuyen",1,"お腹がすいた","onaka ga suita","ô-na-ca ga su-i-ta","đói bụng","お腹がすいた","Onaka ga suita","ô-na-ca ga su-i-ta","Tôi đói rồi"),
  W("camxuc-8","chuyen",1,"のどが渇いた","nodo ga kawaita","nô-đô ga ca-oai-ta","khát nước","のどが渇いた","Nodo ga kawaita","nô-đô ga ca-oai-ta","Tôi khát nước"),
  W("camxuc-9","chuyen",1,"びっくり","bikkuri","bic-cu-li","ngạc nhiên","びっくりしました","Bikkuri shimashita","bic-cu-li xi-ma-xi-ta","Tôi giật mình!"),
  W("camxuc-10","chuyen",1,"大好き","daisuki","đai-su-ki","rất thích","日本が大好き","Nihon ga daisuki","ni-hôn ga đai-su-ki","Tôi cực thích Nhật Bản"),
  W("camxuc-11","chuyen",2,"上手","jōzu","giôô-zu","giỏi / khéo","日本語が上手ですね","Nihongo ga jōzu desu ne","ni-hôn-gô ga giôô-du des nê","Tiếng Nhật của bạn giỏi nhỉ"),
  W("camxuc-12","chuyen",2,"下手","heta","hê-ta","kém / vụng","私は下手です","Watashi wa heta desu","oa-ta-xi oa hê-ta des","Tôi kém lắm"),
  W("camxuc-13","chuyen",2,"恥ずかしい","hazukashii","ha-du-ca-xii","ngại / xấu hổ","恥ずかしいです","Hazukashii desu","ha-du-ca-xii des","Tôi ngại quá"),
  W("camxuc-14","chuyen",2,"心配","shinpai","xim-pai","lo lắng","心配しないで","Shinpai shinaide","xim-pai xi-nai-đê","Đừng lo lắng"),
  W("camxuc-15","chuyen",2,"大変","taihen","đai-hên","vất vả / tệ","大変ですね","Taihen desu ne","đai-hên des nê","Vất vả nhỉ"),
  W("camxuc-16","chuyen",2,"素敵","suteki","su-tê-ki","tuyệt vời","素敵な写真","Suteki na shashin","su-tê-ki na xa-xin","Bức ảnh tuyệt vời"),
  W("camxuc-17","chuyen",2,"楽しみ","tanoshimi","ta-nô-xi-mi","mong chờ","楽しみです","Tanoshimi desu","ta-nô-xi-mi des","Tôi mong chờ lắm"),
  W("camxuc-18","chuyen",2,"頑張る","ganbaru","gan-ba-lu","cố gắng","頑張ってください","Ganbatte kudasai","gan-bat-tê cu-đa-sai","Cố lên nhé!"),
  W("camxuc-19","chao",2,"おめでとう","omedetō","ô-mê-đê-tôô","chúc mừng","おめでとうございます","Omedetō gozaimasu","ô-mê-đê-tôô gô-za-i-ma-su","Chúc mừng bạn!"),
  W("camxuc-20","chuyen",2,"残念","zannen","zan-nên","tiếc quá","残念です","Zannen desu","zan-nên des","Tiếc quá"),
  W("camxuc-21","chuyen",3,"気持ち","kimochi","ki-mô-chi","cảm giác","気持ちがいい","Kimochi ga ii","ki-mô-chi ga ii","Thoải mái quá"),
  W("camxuc-22","chuyen",3,"寂しい","sabishii","sa-bi-xii","cô đơn","寂しいです","Sabishii desu","sa-bi-xii des","Tôi thấy cô đơn"),
  W("camxuc-23","chuyen",3,"眠い","nemui","nê-mui","buồn ngủ","眠いです","Nemui desu","nê-mui des","Buồn ngủ quá"),
  W("camxuc-24","chuyen",3,"かっこいい","kakkoii","câc-côi-ii","ngầu / đẹp trai","かっこいいですね","Kakkoii desu ne","câc-côi-ii des nê","Ngầu thật đấy!"),
  W("camxuc-25","chuyen",3,"興味","kyōmi","cyôô-mi","hứng thú","興味があります","Kyōmi ga arimasu","cyôô-mi ga a-li-mas","Tôi có hứng thú"),
  W("camxuc-26","chuyen",3,"がっかり","gakkari","gâc-ca-li","thất vọng","がっかりしました","Gakkari shimashita","gâc-ca-li xi-ma-xi-ta","Tôi thất vọng"),
  W("camxuc-27","chuyen",3,"ほっとした","hotto shita","hô-t-tô xi-ta","nhẹ nhõm","ほっとしました","Hotto shimashita","hô-t-tô xi-ma-xi-ta","Tôi nhẹ nhõm rồi"),
  W("camxuc-28","chuyen",3,"感謝","kansha","can-xa","biết ơn","感謝しています","Kansha shite imasu","can-xa xi-tê i-mas","Tôi rất biết ơn"),
  W("camxuc-29","chuyen",3,"お世話になりました","osewa ni narimashita","ô-sê-oa ni na-li-ma-xi-ta","cảm ơn đã giúp đỡ","お世話になりました","Osewa ni narimashita","ô-sê-oa ni na-li-ma-xi-ta","Cảm ơn vì đã chăm sóc"),
  W("camxuc-30","chao",3,"お疲れ様","otsukaresama","ô-tsu-ca-lê-sa-ma","vất vả rồi","お疲れ様でした","Otsukaresama deshita","ô-tsu-ca-lê-sa-ma đê-xi-ta","Vất vả cho bạn rồi!"),
  // ===== 10. KHẨN CẤP & SỨC KHỎE (30) =====
  W("suckhoe-21","anuong",3,"アレルギー","arerugī","a-lê-lu-gii","dị ứng","アレルギーがあります","Arerugī ga arimasu","a-lê-lu-gii ga a-li-mas","Tôi bị dị ứng"),
  W("amthuc-1","anuong",1,"すし","sushi","su-xi","sushi","このすしはおいしいです","Kono sushi wa oishii desu","Ko-no su-xi oa ô-i-xii des","Sushi này ngon"),
  W("amthuc-2","anuong",1,"さしみ","sashimi","sa-xi-mi","sashimi (cá sống thái lát)","さしみが好きです","Sashimi ga suki desu","Sa-xi-mi ga su-ki des","Tôi thích sashimi"),
  W("amthuc-3","anuong",1,"てんぷら","tenpura","tên-phu-la","tempura (chiên bột Nhật)","てんぷらをください","Tenpura o kudasai","Tên-phu-la ô cu-đa-sai","Cho tôi tempura"),
  W("amthuc-4","anuong",1,"ラーメン","rāmen","laa-mên","mì ramen","ラーメンが食べたい","Rāmen ga tabetai","Laa-mên ga ta-bê-đai","Tôi muốn ăn ramen"),
  W("amthuc-5","anuong",1,"うどん","udon","u-đôn","mì udon (sợi dày)","うどんをください","Udon o kudasai","U-đôn ô cu-đa-sai","Cho tôi udon"),
  W("amthuc-6","anuong",1,"そば","soba","sô-ba","mì soba (kiều mạch)","そばをください","Soba o kudasai","Sô-ba ô cu-đa-sai","Cho tôi soba"),
  W("amthuc-7","anuong",1,"カレー","karē","ca-lê","cà ri Nhật","カレーはからいですか","Karē wa karai desu ka","Ca-lê oa ca-la-i des ca","Cà ri này cay không?"),
  W("amthuc-8","anuong",2,"とんかつ","tonkatsu","tôn-cat-su","heo chiên xù","とんかつをください","Tonkatsu o kudasai","Tôn-cat-su ô cu-đa-sai","Cho tôi tonkatsu"),
  W("amthuc-9","anuong",2,"やきにく","yakiniku","ya-ki-ni-cu","thịt nướng","やきにくが食べたい","Yakiniku ga tabetai","Ya-ki-ni-cu ga ta-bê-đai","Tôi muốn ăn thịt nướng"),
  W("amthuc-10","anuong",2,"すきやき","sukiyaki","su-ki-ya-ki","sukiyaki (lẩu Nhật)","すきやきはゆうめいです","Sukiyaki wa yūmei desu","Su-ki-ya-ki oa yuu-mêi des","Sukiyaki nổi tiếng"),
  W("amthuc-11","anuong",3,"しゃぶしゃぶ","shabushabu","xa-bu-xa-bu","shabu-shabu (nhúng thịt lẩu)","しゃぶしゃぶをよやくします","Shabushabu o yoyaku shimasu","Xa-bu-xa-bu ô yo-ya-cu xi-mas","Đặt bàn shabushabu"),
  W("amthuc-12","anuong",2,"なべ","nabe","na-bê","lẩu Nhật","なべを食べましょう","Nabe o tabemashō","Na-bê ô ta-bê-ma-xôô","Cùng ăn lẩu nhé"),
  W("amthuc-13","anuong",1,"ジュース","jūsu","juu-su","nước ép / nước ngọt","ジュースをください","Jūsu o kudasai","Juu-su ô cu-đa-sai","Cho tôi nước trái cây"),
  W("amthuc-14","anuong",3,"あげもの","agemono","a-ghê-mô-nô","món chiên","あげものが好きです","Agemono ga suki desu","A-ghê-mô-nô ga su-ki des","Tôi thích món chiên"),
  W("amthuc-15","anuong",3,"むしもの","mushimono","mu-xi-mô-nô","món hấp","このむしものはおいしい","Kono mushimono wa oishii","Ko-no mu-xi-mô-nô oa ô-i-xii","Món hấp này ngon"),
  W("amthuc-16","anuong",3,"にこみ","nikomi","ni-cô-mi","món hầm","にこみをおねがいします","Nikomi o onegai shimasu","Ni-cô-mi ô ô-nê-gai xi-mas","Làm ơn cho món hầm"),
  W("amthuc-17","anuong",2,"しょうゆ","shōyu","xôô-yu","nước tương","しょうゆをください","Shōyu o kudasai","Xôô-yu ô cu-đa-sai","Cho tôi nước tương"),
  W("amthuc-18","anuong",2,"しお","shio","xi-ô","muối","しおラーメンをください","Shio rāmen o kudasai","Xi-ô laa-mên ô cu-đa-sai","Cho tôi ramen muối"),
  W("amthuc-19","anuong",3,"さとう","satō","sa-tôô","đường","さとうはいりません","Satō wa hairimasen","Sa-tôô oa hai-li-ma-sên","Không bỏ đường"),
  W("amthuc-20","anuong",2,"ホット","hotto","hô-t-tô","nóng (đồ uống)","ホットコーヒーをください","Hotto kōhī o kudasai","Hô-t-tô côô-hii ô cu-đa-sai","Cho tôi cà phê nóng"),
  W("amthuc-21","anuong",2,"アイス","aisu","ai-su","lạnh / đá (đồ uống)","アイスティーをください","Aisu tī o kudasai","Ai-su tii ô cu-đa-sai","Cho tôi trà đá"),
  W("amthuc-22","anuong",2,"おおもり","ōmori","ôô-mô-li","phần lớn (cơm/mì)","おおもりをください","Ōmori o kudasai","Ôô-mô-li ô cu-đa-sai","Cho tôi phần lớn"),
  W("amthuc-23","anuong",3,"あまくち","amakuchi","a-ma-cu-chi","vị ngọt / nhạt","カレーはあまくちで","Karē wa amakuchi de","Ca-lê oa a-ma-cu-chi đê","Cà ri cho tôi vị nhẹ"),
  W("amthuc-24","anuong",3,"からくち","karakuchi","ca-la-cu-chi","vị cay đậm","からくちが好きです","Karakuchi ga suki desu","Ca-la-cu-chi ga su-ki des","Tôi thích vị cay đậm"),
  W("diadiem-31","thamquan",2,"温泉","onsen","ôn-sên","suối nước nóng","温泉に行きたい","Onsen ni ikitai","Ôn-sên ni i-ki-đai","Tôi muốn đi tắm onsen"),
  W("diadiem-32","thamquan",2,"お祭り","omatsuri","ô-ma-tsu-li","lễ hội","このお祭りはにぎやかです","Kono omatsuri wa nigiyaka desu","Co-no ô-ma-tsu-li oa ni-gi-ya-ca des","Lễ hội này sôi động"),
  W("diadiem-33","thamquan",2,"花火","hanabi","ha-na-bi","pháo hoa","花火がきれいです","Hanabi ga kirei desu","Ha-na-bi ga ki-lêi des","Pháo hoa đẹp quá"),
  W("diadiem-34","thamquan",1,"桜","sakura","sa-cu-la","hoa anh đào","桜がきれいです","Sakura ga kirei desu","Sa-cu-la ga ki-lêi des","Hoa anh đào đẹp quá"),
  W("diadiem-35","thamquan",2,"城","shiro","xi-lô","lâu đài / thành","この城はゆうめいです","Kono shiro wa yūmei desu","Co-no xi-lô oa yuu-mêi des","Lâu đài này nổi tiếng"),
  W("tinhtu-31","chuyen",3,"すばらしい","subarashii","su-ba-la-xii","tuyệt vời / tuyệt hảo","すばらしい！","Subarashii!","Su-ba-la-xii!","Tuyệt vời luôn!"),
  W("camxuc-31","chuyen",3,"最高","saikō","sai-côô","tuyệt nhất / đỉnh nhất","最高でした！","Saikō deshita!","Sai-côô đê-xi-ta!","Tuyệt nhất luôn!"),
];

/* ---------------- TỪ ĐIỂN CÁCH ĐỌC KANJI (cho bảng "từng chữ → phát âm")
   key = cụm kanji liền nhau · value = [romaji, đọc-kiểu-Việt] · theo ngữ cảnh trong app */
const KANJI_READ = {
  "安心":["anshin","an-xin"],
  "一":["ichi","i-chi"],
  "一度":["ichido","i-chi-đô"],
  "一日":["ichinichi","i-chi-ni-chi"],
  "一枚":["ichimai","i-chi-mai"],
  "一緒":["issho","it-xô"],
  "右":["migi","mi-gi"],
  "駅":["eki","ê-ki"],
  "円":["en","ên"],
  "下手":["heta","hê-ta"],
  "何":["nani","na-ni"],
  "何時":["nanji","nan-gi"],
  "果物":["kudamono","cu-đa-mô-no"],
  "火":["hi","hi"],
  "荷物":["nimotsu","ni-mô-tsu"],
  "改札":["kaisatsu","cai-sat-su"],
  "階段":["kaidan","cai-đan"],
  "角":["kado","ca-đô"],
  "割引":["waribiki","oa-li-bi-ki"],
  "感謝":["kansha","can-xa"],
  "救急車":["kyūkyūsha","cyuu-cyuu-xa"],
  "牛肉":["gyūniku","ghiuu-ni-cu"],
  "魚":["sakana","sa-ca-na"],
  "興味":["kyōmi","cyôô-mi"],
  "緊急":["kinkyū","kin-cyuu"],
  "銀行":["ginkō","ghin-côô"],
  "九":["kyū","cyuu"],
  "空港":["kūkō","cuu-côô"],
  "靴":["kutsu","cu-tsu"],
  "警察":["keisatsu","kêi-sat-su"],
  "警察官":["keisatsukan","kêi-sat-su-can"],
  "鶏肉":["toriniku","tô-li-ni-cu"],
  "血":["chi","chi"],
  "月":["tsuki","tsu-ki"],
  "検査":["kensa","kên-sa"],
  "元気":["genki","ghên-ki"],
  "現金":["genkin","ghên-kin"],
  "五":["go","gô"],
  "午後":["gogo","gô-gô"],
  "午前":["gozen","gô-zên"],
  "交換":["kōkan","côô-can"],
  "交番":["kōban","côô-ban"],
  "今":["ima","i-ma"],
  "今週":["konshū","con-xuu"],
  "今日":["kyō","cyôô"],
  "今晩":["konban","con-ban"],
  "左":["hidari","hi-đa-li"],
  "在庫":["zaiko","zai-cô"],
  "財布":["saifu","sai-phu"],
  "昨日":["kinō","ki-nôô"],
  "三":["san","san"],
  "傘":["kasa","ca-sa"],
  "残念":["zannen","zan-nên"],
  "四":["yôn","yôn"],
  "事故":["jiko","gi-cô"],
  "時間":["jikan","gi-can"],
  "七":["nana","na-na"],
  "受付":["uketsuke","u-kê-tsu-kê"],
  "週末":["shūmatsu","xuu-mat-su"],
  "十":["jū","juu"],
  "祝日":["shukujitsu","xu-cu-gi-tsu"],
  "出口":["deguchi","đê-gu-chi"],
  "小銭":["kozeni","co-zê-ni"],
  "消防車":["shōbōsha","xôô-bôô-xa"],
  "上手":["jōzu","giôô-zu"],
  "色":["iro","i-lô"],
  "心配":["shinpai","xim-pai"],
  "新幹線":["shinkansen","xin-can-sên"],
  "神社":["jinja","gin-đa"],
  "水":["mizu","mi-zu"],
  "正午":["shōgo","xôô-gô"],
  "切符":["kippu","kip-phu"],
  "千":["sen","sên"],
  "前日":["zenjitsu","zên-gi-tsu"],
  "全然":["zenzen","zên-zên"],
  "全部":["zenbu","zên-bu"],
  "素敵":["suteki","su-tê-ki"],
  "待合室":["machiaishitsu","ma-chi-ai-xi-tsu"],
  "袋":["fukuro","phu-cu-lô"],
  "大使館":["taishikan","đai-xi-can"],
  "大変":["taihen","đai-hên"],
  "値札":["nefuda","nê-phu-đa"],
  "値段":["nedan","nê-đan"],
  "地震":["jishin","gi-xin"],
  "地図":["chizu","chi-zu"],
  "昼":["hiru","hi-lu"],
  "注射":["chūsha","chuu-xa"],
  "朝":["asa","a-sa"],
  "店":["mise","mi-sê"],
  "電車":["densha","đên-xa"],
  "電話":["denwa","đên-oa"],
  "当日":["tōjitsu","tôô-gi-tsu"],
  "豚肉":["butaniku","bu-ta-ni-cu"],
  "二":["ni","ni"],
  "肉":["niku","ni-cu"],
  "入口":["iriguchi","i-li-gu-chi"],
  "熱":["netsu","nê-tsu"],
  "年":["toshi","tô-xi"],
  "博物館":["hakubutsukan","ha-cu-but-su-can"],
  "箱":["hako","ha-cô"],
  "八":["hachi","ha-chi"],
  "半額":["hangaku","han-ga-cu"],
  "半分":["hanbun","han-bun"],
  "番号":["bangō","ban-gôô"],
  "避難":["hinan","hi-nan"],
  "百":["hyaku","hya-cu"],
  "氷":["kōri","côô-li"],
  "病院":["byōin","byôô-in"],
  "病気":["byōki","byôô-ki"],
  "風邪":["kaze","ca-zê"],
  "服":["fuku","phu-cu"],
  "分":["fun","phun"],
  "平日":["heijitsu","hêi-gi-tsu"],
  "返品":["henpin","hên-pin"],
  "便利":["benri","bên-li"],
  "弁当":["bentō","bên-tôô"],
  "保険":["hoken","hô-kên"],
  "本":["hon","hôn"],
  "毎日":["mainichi","mai-ni-chi"],
  "万":["man","man"],
  "味噌汁":["misoshiru","mi-xô-xi-lu"],
  "名物":["meibutsu","mêi-phu-tsu"],
  "明後日":["asatte","a-sat-tê"],
  "明日":["ashita","a-xi-ta"],
  "迷子":["maigo","mai-gô"],
  "夜":["yoru","yô-lu"],
  "野菜":["yasai","ya-sai"],
  "約":["yaku","ya-cu"],
  "薬":["kusuri","cu-su-li"],
  "薬局":["yakkyoku","yac-cyô-cu"],
  "有名":["yūmei","yuu-mêi"],
  "予定":["yotei","yô-têi"],
  "来週":["raishū","lai-xuu"],
  "卵":["tamago","ta-ma-gô"],
  "両替":["ryōgae","lyôô-ga-ê"],
  "領収書":["ryōshūsho","lyôô-xuu-xô"],
  "六":["roku","lô-cu"],
  // --- kanji nằm trong cụm câu/dòng kana ---
  "悪":["wa","oa"],
  "安":["yasu","ya-su"],
  "飲":["no","nô"],
  "英語":["eigo","êi-gô"],
  "遠":["tō","tô"],
  "遠慮":["enryo","ên-lyô"],
  "会計":["kaikei","cai-kê"],
  "開":["a","a"],
  "楽":["tano","ta-nô"],
  "渇":["kawa","ca-oa"],
  "寒":["sa","sa"],
  "甘":["ama","a-ma"],
  "頑張":["ganba","gan-ba"],
  "願":["nega","nê-ga"],
  "危":["abuna","a-bu-na"],
  "嬉":["ure","u-lê"],
  "気持":["kimochi","ki-mô-chi"],
  "気分":["kibun","ki-bun"],
  "休":["yasu","ya-su"],
  "教":["oshie","ô-xiê"],
  "狭":["sema","sê-ma"],
  "近":["chika","chi-ca"],
  "金":["kane","ca-nê"],
  "軽":["karu","ca-lu"],
  "決":["kime","ki-mê"],
  "見":["mi","mi"],
  "古":["furu","phu-lu"],
  "呼":["yo","yô"],
  "後":["ato","a-tô"],
  "向":["mu","mu"],
  "好":["su","su"],
  "広":["hiro","hi-lô"],
  "行":["i","i"],
  "降":["o","ô"],
  "高":["taka","ta-ca"],
  "撮":["to","tô"],
  "使":["tsuka","tsu-ca"],
  "止":["to","tô"],
  "試着":["shichaku","xi-chac"],
  "寺":["tera","tê-la"],
  "持":["mo","mô"],
  "治":["nao","na-ô"],
  "寂":["sabi","sa-bi"],
  "取":["to","tô"],
  "手続":["tetsuduki","tê-tsu-zu-ki"],
  "手伝":["tetsuda","tê-tsu-đa"],
  "酒":["sake","sa-kê"],
  "集":["atsuma","at-su-ma"],
  "重":["omo","ô-mô"],
  "暑":["atsu","at-su"],
  "書":["ka","ca"],
  "助":["tasu","ta-su"],
  "小":["chī","chii"],
  "少":["suko","su-cô"],
  "乗":["no","nô"],
  "場":["ba","ba"],
  "食":["ta","ta"],
  "新":["atara","a-ta-la"],
  "辛":["kara","ca-la"],
  "世話":["sewa","sê-oa"],
  "青":["a","a"],
  "静":["shizu","xi-zu"],
  "税込":["zeikomi","zêi-ko-mi"],
  "赤":["aka","a-ca"],
  "待":["ma","ma"],
  "替":["kae","ca-ê"],
  "大":["ō","ôô"],
  "大好":["daisu","đai-su"],
  "大阪":["ōsaka","ôô-sa-ca"],
  "大丈夫":["daijōbu","đai-giôô-bu"],
  "探":["sagashi","sa-ga-xi"],
  "恥":["hazukashi","ha-du-ca-xi"],
  "茶":["cha","cha"],
  "痛":["ita","i-đa"],
  "釣":["tsuri","tsu-li"],
  "土産":["miyage","mi-ya-gê"],
  "東京駅行":["tōkyōekiyu","tôô-kyôô-ê-ki-yu"],
  "湯":["yu","yu"],
  "道":["michi","mi-chi"],
  "読":["yo","yô"],
  "難":["muzuka","mu-zu-ca"],
  "日本語":["nihongo","ni-hôn-gô"],
  "買":["ka","ca"],
  "売":["uri","u-li"],
  "飯":["han","han"],
  "悲":["kana","ca-na"],
  "疲":["tsukare","tsu-ca-lê"],
  "腹":["naka","na-ca"],
  "払":["hara","ha-la"],
  "物":["mono","mô-nô"],
  "聞":["ki","ki"],
  "閉":["shime","xi-mê"],
  "忘":["wasure","oa-su-lê"],
  "眠":["nemu","nê-mu"],
  "名前":["namae","na-ma-ê"],
  "迷":["mayo","ma-yo"],
  "免税":["menzei","mên-zê"],
  "面白":["omoshiro","ô-mô-xi-lô"],
  "予約":["yoyaku","yo-ya-cu"],
  "様":["sama","sa-ma"],
  "来":["ki","ki"],
  "落":["otoshi","ô-tô-xi"],
  "涼":["suzu","su-zu"],
  "話":["hanashi","ha-na-xi"],
  "乾杯":["kanpai","can-pai"],
  "写真":["shashin","xa-xin"],
  "温泉":["onsen","ôn-sên"],
  "祭":["matsuri","ma-tsu-li"],
  "花火":["hanabi","ha-na-bi"],
  "桜":["sakura","sa-cu-la"],
  "城":["shiro","xi-lô"],
  "最高":["saikō","sai-côô"],
};

/* ---------------- MINH HỌA TỪNG THẺ (dual coding) ----------------
   Mỗi thẻ 1 emoji làm hình; câu = cảnh nhỏ 1-2 emoji. Muốn dùng ảnh AI tự tạo:
   thêm "id": "img/ten.webp" vào IMG_OVERRIDE (app.js) — sẽ ưu tiên hơn emoji. */
const ILLUS = {
  g1:"🙇", g2:"🌅", g3:"🌙", g4:"👋", g5:"✌️", g6:"🙏", g7:"🙋", g8:"😔", g9:"🤝", g10:"😴",
  e1:"⭕", e2:"❌", e3:"🗣️", e4:"🤷", e5:"🐢", e6:"💴", e7:"🚻", e8:"💳", e9:"🆘", e10:"👌",
  r1:"👉", r2:"📋", r3:"💧", r4:"🍺", r5:"🍽️🙏", r6:"🧾", r7:"🍽️😋", r8:"⭐", r9:"🥩🙅", r10:"🌶️",
  s1:"🏷️", s2:"👚", s3:"💸", s4:"📉", s5:"🛒", s6:"👀", s7:"🛍️", s8:"🈹",
  d1:"🚉", d2:"🧭", d3:"⬅️", d4:"➡️", d5:"⬆️", d6:"🛣️", d7:"🗺️", d8:"🛑", d9:"🚅", d10:"🎫",
  h1:"📅", h2:"🏨", h3:"⏰", h4:"📶", h5:"🚑", h6:"🛂", h7:"🏥", h8:"🤒",
  n1:"1️⃣2️⃣3️⃣", n2:"4️⃣5️⃣6️⃣", n3:"7️⃣8️⃣9️⃣", n4:"🔟", n5:"💯", n6:"🏦", n7:"💰", n8:"🎧",
  t1:"🪪", t2:"🇻🇳", t3:"✈️", t4:"🍣", t5:"😋", t6:"🤩", t7:"✨", t8:"📅👋", t9:"🌞", t10:"😅",
  "vanuong-1":"💧", "vanuong-2":"🍵", "vanuong-3":"☕", "vanuong-4":"🍚", "vanuong-5":"🍞", "vanuong-6":"🥩", "vanuong-7":"🐟", "vanuong-8":"🥬", "vanuong-9":"🍎", "vanuong-10":"🥚",
  "vanuong-11":"🍺", "vanuong-12":"🍶", "vanuong-13":"🐄", "vanuong-14":"🐷", "vanuong-15":"🐔", "vanuong-16":"🍲", "vanuong-17":"🍱", "vanuong-18":"🍙", "vanuong-19":"🍮", "vanuong-20":"🍦",
  "vanuong-21":"🥣", "vanuong-22":"🥗", "vanuong-23":"🧀", "vanuong-24":"🍅", "vanuong-25":"🍊", "vanuong-26":"🍓", "vanuong-27":"♨️", "vanuong-28":"🧊", "vanuong-29":"🥤", "vanuong-30":"➕",
  "sotien-1":"1️⃣", "sotien-2":"2️⃣", "sotien-3":"3️⃣", "sotien-4":"4️⃣", "sotien-5":"5️⃣", "sotien-6":"6️⃣", "sotien-7":"7️⃣", "sotien-8":"8️⃣", "sotien-9":"9️⃣", "sotien-10":"🔟",
  "sotien-11":"💯", "sotien-12":"🏦", "sotien-13":"💰", "sotien-14":"🪙", "sotien-15":"🕐", "sotien-16":"💳", "sotien-17":"💴", "sotien-18":"🏷️", "sotien-19":"💵", "sotien-20":"🪙",
  "sotien-21":"➗", "sotien-22":"📦", "sotien-23":"💱", "sotien-24":"🈹", "sotien-25":"🧮", "sotien-26":"🪙", "sotien-27":"🔁", "sotien-28":"🎯", "sotien-29":"〰️", "sotien-30":"🧾",
  "thoigian-1":"📅", "thoigian-2":"🌤️", "thoigian-3":"🌘", "thoigian-4":"🌗", "thoigian-5":"⏱️", "thoigian-6":"🌄", "thoigian-7":"🌞", "thoigian-8":"🌙", "thoigian-9":"⌛", "thoigian-10":"⏱️",
  "thoigian-11":"📆", "thoigian-12":"🗓️", "thoigian-13":"🏖️", "thoigian-14":"🌕", "thoigian-15":"🎍", "thoigian-16":"☀️", "thoigian-17":"🌤️", "thoigian-18":"🔁", "thoigian-19":"🛌", "thoigian-20":"🕛",
  "thoigian-21":"🌃", "thoigian-22":"🚦", "thoigian-23":"🎌", "thoigian-24":"🏢", "thoigian-25":"🗒️", "thoigian-26":"💨", "thoigian-27":"🔜", "thoigian-28":"⏭️", "thoigian-29":"🎟️", "thoigian-30":"⏮️",
  "diadiem-1":"🚉", "diadiem-2":"✈️", "diadiem-3":"🚻", "diadiem-4":"🏪", "diadiem-5":"🏨", "diadiem-6":"🏦", "diadiem-7":"🍽️", "diadiem-8":"🚌", "diadiem-9":"🚕", "diadiem-10":"🚃",
  "diadiem-11":"🗺️", "diadiem-12":"🚅", "diadiem-13":"🎫", "diadiem-14":"🚪", "diadiem-15":"🚉", "diadiem-16":"🏥", "diadiem-17":"💊", "diadiem-18":"👮", "diadiem-19":"⛩️", "diadiem-20":"🏯",
  "diadiem-21":"🏛️", "diadiem-22":"🚪", "diadiem-23":"🚪", "diadiem-24":"🚏", "diadiem-25":"🪜", "diadiem-26":"🛗", "diadiem-27":"🧳", "diadiem-28":"📍", "diadiem-29":"👉", "diadiem-30":"↪️",
  "dogvat-1":"👆", "dogvat-2":"👉", "dogvat-3":"🫵", "dogvat-4":"👛", "dogvat-5":"🎒", "dogvat-6":"📱", "dogvat-7":"📷", "dogvat-8":"📚", "dogvat-9":"☂️", "dogvat-10":"👟",
  "dogvat-11":"👕", "dogvat-12":"👕", "dogvat-13":"📐", "dogvat-14":"🎨", "dogvat-15":"🏬", "dogvat-16":"🏬", "dogvat-17":"💊", "dogvat-18":"🎁", "dogvat-19":"🛍️", "dogvat-20":"🧾",
  "dogvat-21":"🏷️", "dogvat-22":"📦", "dogvat-23":"🛍️", "dogvat-24":"🉐", "dogvat-25":"⭐", "dogvat-26":"📦", "dogvat-27":"🎀", "dogvat-28":"🔄", "dogvat-29":"↩️", "dogvat-30":"🍡",
  "dongtu-1":"🍜", "dongtu-2":"🥤", "dongtu-3":"🚶", "dongtu-4":"🏃", "dongtu-5":"🛒", "dongtu-6":"👀", "dongtu-7":"👂", "dongtu-8":"💬", "dongtu-9":"📖", "dongtu-10":"✍️",
  "dongtu-11":"⚙️", "dongtu-12":"💡", "dongtu-13":"🚏", "dongtu-14":"🚪", "dongtu-15":"🪑", "dongtu-16":"🛌", "dongtu-17":"🔌", "dongtu-18":"🤲", "dongtu-19":"📣", "dongtu-20":"🤝",
  "dongtu-21":"🔍", "dongtu-22":"📸", "dongtu-23":"🔓", "dongtu-24":"🔒", "dongtu-25":"📌", "dongtu-26":"🧑‍🤝‍🧑", "dongtu-27":"🫥", "dongtu-28":"🔃", "dongtu-29":"📅", "dongtu-30":"🙅",
  "tinhtu-1":"😋", "tinhtu-2":"📈", "tinhtu-3":"📉", "tinhtu-4":"⬛", "tinhtu-5":"▪️", "tinhtu-6":"🌟", "tinhtu-7":"🏚️", "tinhtu-8":"👍", "tinhtu-9":"🥰", "tinhtu-10":"🎉",
  "tinhtu-11":"🥵", "tinhtu-12":"🥶", "tinhtu-13":"🌶️", "tinhtu-14":"🍬", "tinhtu-15":"📍", "tinhtu-16":"🛣️", "tinhtu-17":"😫", "tinhtu-18":"💗", "tinhtu-19":"🔴", "tinhtu-20":"🔵",
  "tinhtu-21":"🤫", "tinhtu-22":"🛠️", "tinhtu-23":"👑", "tinhtu-24":"🎈", "tinhtu-25":"🏋️", "tinhtu-26":"🏞️", "tinhtu-27":"🤏", "tinhtu-28":"💮", "tinhtu-29":"⚠️", "tinhtu-30":"🍃",
  "cauhoi-1":"❓", "cauhoi-2":"🧭", "cauhoi-3":"👤", "cauhoi-4":"💴", "cauhoi-5":"🤔", "cauhoi-6":"⏰", "cauhoi-7":"❔", "cauhoi-8":"🤲", "cauhoi-9":"✋", "cauhoi-10":"❗",
  "cauhoi-11":"🔢", "cauhoi-12":"↔️", "cauhoi-13":"🃏", "cauhoi-14":"⁉️", "cauhoi-15":"🤞", "cauhoi-16":"🎖️", "cauhoi-17":"➡️", "cauhoi-18":"🤨", "cauhoi-19":"🔀", "cauhoi-20":"⏭️",
  "cauhoi-21":"💡", "cauhoi-22":"🙆", "cauhoi-23":"🔹", "cauhoi-24":"🆖", "cauhoi-25":"🏁", "cauhoi-26":"🚧", "cauhoi-27":"🧑‍🤝‍🧑", "cauhoi-28":"♾️", "cauhoi-29":"🪄", "cauhoi-30":"💪",
  "camxuc-1":"💪", "camxuc-2":"😮‍💨", "camxuc-3":"🥳", "camxuc-4":"😢", "camxuc-5":"🤣", "camxuc-6":"😑", "camxuc-7":"🍽️", "camxuc-8":"🧃", "camxuc-9":"😲", "camxuc-10":"❤️",
  "camxuc-11":"🏅", "camxuc-12":"😬", "camxuc-13":"😳", "camxuc-14":"😟", "camxuc-15":"😩", "camxuc-16":"💖", "camxuc-17":"🤗", "camxuc-18":"✊", "camxuc-19":"🎊", "camxuc-20":"😞",
  "camxuc-21":"😌", "camxuc-22":"🥺", "camxuc-23":"😴", "camxuc-24":"😎", "camxuc-25":"🧐", "camxuc-26":"😕", "camxuc-27":"😌", "camxuc-28":"🙏", "camxuc-29":"🙇‍♀️", "camxuc-30":"🍵",
  "suckhoe-21":"🥜", "suckhoe-22":"🩸", "suckhoe-23":"🛎️", "suckhoe-24":"🪑", "suckhoe-25":"💚", "suckhoe-26":"🩺", "suckhoe-27":"💉", "suckhoe-28":"🕊️", "suckhoe-29":"❗", "suckhoe-30":"🏃",
  r11:"🙏🍚", r12:"🥢", r13:"🍻", r14:"🥗", g11:"😊", t11:"🌟", d11:"📸",
  "amthuc-1":"🍣", "amthuc-2":"🐟", "amthuc-3":"🍤", "amthuc-4":"🍜", "amthuc-5":"🍲", "amthuc-6":"🥢", "amthuc-7":"🍛", "amthuc-8":"🍖", "amthuc-9":"🥩", "amthuc-10":"🫕", "amthuc-11":"🍲", "amthuc-12":"🥘", "amthuc-13":"🧃", "amthuc-14":"🍤", "amthuc-15":"♨️", "amthuc-16":"🍲", "amthuc-17":"🍶", "amthuc-18":"🧂", "amthuc-19":"🍬", "amthuc-20":"☕", "amthuc-21":"🧊", "amthuc-22":"🍚", "amthuc-23":"🍯", "amthuc-24":"🌶️",
  "diadiem-31":"♨️", "diadiem-32":"🎪", "diadiem-33":"🎆", "diadiem-34":"🌸", "diadiem-35":"🏯",
  "tinhtu-31":"🌟", "camxuc-31":"🔝",
};

/* ---------------- DỮ LIỆU KHÁC ---------------- */
const HIRAGANA = [
  ["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"],
  ["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"],
  ["さ","sa"],["し","shi"],["す","su"],["せ","se"],["そ","so"],
  ["た","ta"],["ち","chi"],["つ","tsu"],["て","te"],["と","to"],
  ["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"],
  ["は","ha"],["ひ","hi"],["ふ","fu"],["へ","he"],["ほ","ho"],
  ["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"],
  ["や","ya"],["ゆ","yu"],["よ","yo"],
  ["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"],
  ["わ","wa"],["を","o"],["ん","n"],
];

const EMOJIS = ["🐱","🦊","🐼","🐸","🐵","🐰","🦁","🐯","🐨","🐷","🐧","🦄","🐙","🥷","🧑‍🍳","🍡","🍙","🌸","🗼","🍥","🏯","⛩️","🍣","🌺"];
const AVA_COLORS = ["#ffe3ec","#dff0fa","#e3f2dc","#fff3d6","#ece4fa","#ffe9d6"];

const TIPS_HOME = [
  "Mẹo: 'Sumimasen' là cây đa năng — xin lỗi, gọi phục vụ, hỏi đường đều dùng được!",
  "Mẹo: Chỉ vào menu + 'Kore o kudasai' = ăn được ở bất cứ đâu 🍜",
  "Mẹo: Động từ luôn đứng CUỐI câu. Nhớ 1 quy tắc này là tự tin nửa đường!",
  "Mẹo: Học 10 phút mỗi ngày hiệu quả hơn 1 giờ mỗi tuần 🌸",
  "Mẹo: Nói to theo dòng 'đọc kiểu Việt' trước, rồi nghe giọng chuẩn 🔊",
  "Mẹo: いただきます trước khi ăn và ごちそうさまでした khi về — đầu bếp rất vui!",
];
